databricks/dbt-databricks

.bumpversion.cfg
.github/workflows/release.yml
dbt/adapters/databricks/__version__.py
setup.py

Sync with upstream

---

dbt/adapters/databricks/__version__.py

Fixes version to follow dbt-core.

Fix version to follow dbt-core.

---

dbt/include/databricks/macros/materializations/incremental/strategies.sql
dbt/include/databricks/macros/materializations/snapshot.sql

Cleans up more unmodified macros.
- `dbt_databricks_get_insert_into_sql`
- `databricks_build_snapshot_staging_table`

Clean up more unmodified macros

---

.github/workflows/main.yml
dbt/adapters/databricks/connections.py
tests/unit/test_adapter.py

Allow session properties to be set as part of the profile configuration
Will update the README and docs in a separate commit.

Get the session_properties map to work.

---

.github/workflows/main.yml
black.ini
dbt/include/databricks/macros/adapters.sql
dbt/include/databricks/macros/materializations/incremental/incremental.sql
dbt/include/databricks/macros/materializations/table.sql
mypy.ini
scripts/build-dist.sh
setup.py
tests/integration/base.py
tests/integration/conftest.py
tests/integration/current_catalog/test_current_catalog.py
tests/integration/get_columns_in_relation/models/get_columns_from_child.sql
tests/integration/incremental_on_schema_change/models/incremental_append_new_columns.sql
tests/integration/incremental_on_schema_change/models/incremental_append_new_columns_target.sql
tests/integration/incremental_on_schema_change/models/incremental_ignore_target.sql
tests/integration/incremental_on_schema_change/models/incremental_sync_all_columns.sql
tests/integration/incremental_on_schema_change/models/incremental_sync_all_columns_target.sql
tests/integration/incremental_on_schema_change/models/model_a.sql
tests/integration/incremental_on_schema_change/test_incremental_on_schema_change.py
tests/integration/incremental_strategies/test_incremental_strategies.py
tests/integration/persist_docs/models/schema.yml
tests/integration/persist_docs/test_persist_docs.py
tests/integration/seed_column_types/test_seed_column_types.py
tests/integration/set_tblproperties/test_set_tblproperties.py
tests/integration/store_failures/test_store_failures.py
tests/unit/test_adapter.py
tests/unit/test_column.py
tests/unit/test_macros.py
tests/unit/utils.py
tox.ini

Applies black formatter and flake8/mypy check for tests.
Also removed spaces at the end of the line in the whole codebase.

Apply black formatter and flake8/mypy check for tests.

---

dev_requirements.txt
requirements.txt

Fixes the dependencies to see `1.0.latest` branches.

Fix the dependencies to see 1.0.latest branches.

---

dbt/adapters/databricks/__version__.py
dev_requirements.txt
requirements.txt
setup.py

Bumps up version to `1.1.0b1.dev0`.

Bump up version to 1.1.0b1.dev0

---

.github/workflows/main.yml
CHANGELOG.md
dbt/adapters/databricks/__version__.py
requirements.txt
setup.py

Bump version to 1.2.0a1

---

.github/workflows/main.yml
dbt/adapters/databricks/__version__.py
requirements.txt
setup.py
tests/functional/adapter/test_basic.py

Backports and bump version.
- Part of [Bump version to 1.2.0a1](https://github.com/databricks/dbt-databricks/pull/77)
- [Add TestBaseAdapterMethodDatabricks.](https://github.com/databricks/dbt-databricks/pull/78)

Backport and bump version.

---

tests/conftest.py
tests/integration/base.py
tests/utils.py

Fixes UC base tests to use test catalogs.
When porting testing framework, the catalog settings were lost.

Fix UC base tests to use test catalogs.

---

requirements.txt
setup.py

Reject databricks-sql-connector 2.0.0 as it had a dependency issue.

Reject databricks-sql-connector 2.0.0

---

dbt/adapters/databricks/connections.py

Show more error details

---

.github/workflows/main.yml

Fixes the package build test on windows.

Fix the package build test on windows.

---

dbt/adapters/databricks/connections.py

Prints debug log when connection fails.

Print debug log when connection fails

---

tests/integration/set_tblproperties/snapshots/snapshot.sql
tests/integration/set_tblproperties/test_set_tblproperties.py

Adds a test to check if tblproperties works on snapshots.

Add a test to check if tblproperties works on snapshots.

---

dbt/adapters/databricks/connections.py
tests/unit/test_adapter.py

Reverts #106 to follow dbt-labs/dbt-spark#378.

Revert #106

---

CHANGELOG.md
tests/functional/adapter/utils/test_data_types.py

Ports tests in the upstream: Data type macros (dbt-labs/dbt-spark#380)

Port: Data type macros (dbt-labs/dbt-spark#380)

---

.github/workflows/main.yml
setup.py

Adds Python 3.10 to CI as per an item from #127.

Add Python 3.10 to CI

---

CHANGELOG.md
dbt/include/databricks/macros/materializations/incremental/incremental.sql
dbt/include/databricks/macros/materializations/snapshot.sql
dbt/include/databricks/macros/materializations/table.sql
test.env.example
tests/functional/adapter/test_grants.py

Ports in the upstream: Add apply_grants call to materialization macros (dbt-labs/dbt-spark#381).

Port: Add apply_grants call to materialization macros (dbt-labs/dbt-spark#381)

---

.github/workflows/main.yml

Updates CI `pip` by porting dbt-labs/dbt-spark#403 and dbt-labs/dbt-spark#405.

Update CI pip.

---

dev-requirements.txt

Upgrades `mypy` to `0.950` and reorganize `dev-requirements.txt` file.

Upgrade mypy to 0.950 and reorganize dev-requirements.txt file

---

dbt/adapters/databricks/connections.py
tests/unit/test_adapter.py

Include the value of environment variable "DBT_DATABRICKS_INVOCATION_ENV" to the user agent entry.

Include the value of environment variable "DBT_DATABRICKS_INVOCATION_ENV" to the user agent entry.

---

dbt/adapters/databricks/__version__.py
dev-requirements.txt
requirements.txt
setup.py

Bumps version to `1.3.0b0.dev0` and pins upstreams to `1.3.0b2`.

Bump version to 1.3.0b0.dev0 and pin upstreams to 1.3.0b2.

---

dev-requirements.txt
tox.ini

Fix integration tests.

---

dbt/adapters/databricks/__init__.py
dbt/adapters/databricks/connections.py
dbt/adapters/databricks/impl.py
dbt/adapters/databricks/relation.py
dev-requirements.txt
mypy.ini
tests/integration/persist_constraints/test_persist_constraints.py

Removes pins on upstreams and fixes mypy.

Remove pins on upstreams and fix mypy.

---

dbt/adapters/databricks/connections.py
tests/unit/test_adapter.py

Pass http_headers with jobId and runId

Pass http_headers in dbsql.connect

---

dbt/adapters/databricks/connections.py
dbt/adapters/databricks/impl.py

Improves the credential check.
It will show a consistent error message when missing the required fields, `host`, `http_path`, and `token`.
For example:
```
The config 'host' is required to connect to Databricks
```

Improve the credential check.

---

tests/functional/adapter/test_python_model.py

Removes Koalas related tests that was added at https://github.com/dbt-labs/dbt-core/commit/e58edaab2deba8bb14396f463489adf0e1e02e6e.
We won't encourage users to use Koalas any more.

Remove Koalas related tests.

---

tests/functional/adapter/utils/test_utils.py

Add tests for "Array macros" at dbt-labs/dbt-spark#454.

Add tests for "Array macros".

---

tests/functional/adapter/utils/test_utils.py

Adds a test for `current_timestamp` at dbt-labs/dbt-spark#475.

Add a test for `current_timestamp`.

---

tests/integration/incremental_strategies/models_delta/merge_exclude_columns.sql
tests/integration/incremental_strategies/seeds/expected_exclude_upsert.csv
tests/integration/incremental_strategies/test_incremental_strategies.py

Adds a test for "merge exclude columns spark" at dbt-labs/dbt-spark#390.

Add a test for "merge exclude columns spark".

---

black.ini
dev-requirements.txt

Bumps `black` and `mypy`.
- `black` from `22.3.0` to `22.8.0`
- `mypy` from `0.950` to `0.971`

Bump black and mypy.

---

tests/integration/copy_into/test_copy_into.py

This PR removes the SQL warehouse test for COPY INTO since it does not support creating non-Delta table.

Remove COPY INTO SQL warehouse test

---

tests/functional/adapter/utils/test_timestamps.py

Adds a test for "consolidate timestamp macros" at dbt-labs/dbt-spark#480.

Add a test for "consolidate timestamp macros".

---

dbt/adapters/databricks/python_submissions.py

Adds `catalog` to the work dir path for the case where there are the same name schema in different catalogs.
The work dir will be `"/Shared/dbt_python_model/{schema}/"` without `catalog`, and `"/Shared/dbt_python_model/{catalog}/{schema}/"` with `catalog`.

Add catalog to the work dir path.

---

tests/functional/adapter/test_basic.py
tests/functional/adapter/test_concurrency.py
tests/functional/adapter/test_ephemeral.py

Adds missing tests based on new common tests introduced in `dbt-core`:
- `BaseIncrementalNotSchemaChange`
- `BaseConcurrency`
- `BaseEphemeralMulti`

Add missing tests.

---

dbt/include/databricks/macros/copy_into.sql

resolves #
This PR removes info logging in COPY INTO.

Remove logging in COPY INTO

---

dbt/adapters/databricks/connections.py

Close cursors more safely.

---

dbt/include/databricks/macros/copy_into.sql
tests/integration/copy_into/models/expected_target.sql
tests/integration/copy_into/models/source.sql
tests/integration/copy_into/models/target.sql

Replace tabs to spaces.

---

.github/workflows/main.yml

Upgrades `actions/setup-python` from `v2` to `v4.3.0`, following dbt-labs/dbt-spark#508.

Upgrade actions/setup-python from v2 to v4.3.0.

---

dbt/adapters/databricks/impl.py

Supports new error messages.
In `SparkAdapter.get_columns_in_relation`, it checks the error message when the specified table or view doesn't exist:
https://github.com/dbt-labs/dbt-spark/blob/c87b6b2c48bcefb0ce52cd64984d3129d6f14ea0/dbt/adapters/spark/impl.py#L223
but, Spark will change the error message in the future release (apache/spark#37887), which causes the function to raise the `dbt.exceptions.RuntimeException` instead of returning an empty list.
The function should also check whether the error message contains `[TABLE_OR_VIEW_NOT_FOUND]` or not.
This will be reverted once dbt-labs/dbt-spark#515 is resolved.

Support new error messages.

---

README.md
docs/uc.md

Documentation how to use dbt-databricks with Unity Catalog.

Docs for Unity Catalog

---

tests/unit/utils.py
tox.ini

Fixes `tox.ini` to support the latest `tox`.

Fix tox.ini to support the latest tox.

---

.github/workflows/main.yml
CHANGELOG.md
dbt/adapters/databricks/relation.py
setup.py

Support Python 3.11

---

dev-requirements.txt
mypy.ini
tests/integration/base.py
tox.ini

Upgrade mypy to 0.991.

---

black.ini
dev-requirements.txt

Upgrades `black` to `22.12.0`.

Upgrade black to 22.12.0.

---

requirements.txt
setup.py

Upgrades `databricks-sql-connector` to `2.2.2`.
It includes:
- Add tests for parameter sanitisation / escaping (databricks/databricks-sql-python#46) for the fix for #249
- Support Python 3.11 (databricks/databricks-sql-python#60)

Upgrade databricks-sql-connector to 2.2.2

---

dbt/adapters/databricks/connections.py
tests/integration/multi_catalog/snapshots/snapshot.sql

Adds an alias name "target_catalog" for "target_database".

Add an alias name "target_catalog" for "target_database".

---

tests/functional/adapter/test_changing_relation_type.py
tests/functional/adapter/test_query_comment.py

Adds more integration tests provided at dbt-labs/dbt-core#6624.
- test_query_comment.py for "Query Comment Tests"
- test_changing_relation_type.py for "TestChangeRelationTypes"

Add more integration tests provided by dbt-core.

---

.github/pull_request_template.md
CONTRIBUTING.MD

Strictly a documentation change:
N/A this is a non-code change

Add CONTRIBUTING.md

---

.github/workflows/integration.yml

Updates the integration test workflow to run on any push to this repository.

Run integration tests on pushes to branches of this repo (not forks)

---

dbt/adapters/databricks/__version__.py
dev-requirements.txt
requirements.txt
setup.py
tox.ini

1.5.integration tests

---

dbt/adapters/databricks/connections.py
requirements.txt
setup.py

Clone of #349 so we can run e2e tests.

[staging] feat: bump databricks-sdk v0.1.7 and rename RefreshableCredentials to SessionCredentials 

---

dbt/adapters/databricks/connections.py
dbt/include/databricks/macros/adapters.sql
dbt/include/databricks/macros/materializations/materialized_view/create_materialized_view_as.sql
dbt/include/databricks/macros/materializations/seeds/seeds.sql
dbt/include/databricks/macros/materializations/streaming_table/create_or_refresh_streaming_table_as.sql
dbt/include/databricks/macros/materializations/streaming_table/streaming_table.sql
dbt/include/databricks/macros/materializations/view.sql

Polling based on pipeline update status.

Updates to pipeline polling

---

dbt/adapters/databricks/connections.py

Cleanup of logging and error messages.

Cleanup logging/error messages

---

CHANGELOG.md
dbt/adapters/databricks/python_submissions.py
tests/unit/python/test_python_submissions.py

Resolves #368 
Needed to change expected value from "Running" to "RUNNING".  Added unit test of same.

Fix connection issue

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Since we just released version 1.5.5 we can develop version 1.5.6 and update our changelog.

Bump version on main and update changelog

---

.github/workflows/main.yml
CHANGELOG.md
dbt/adapters/databricks/__version__.py
dbt/adapters/databricks/connections.py
dev-requirements.txt
requirements.txt
setup.py

Updated version to 1.6.0rc2 and updated changelog
Updated dbt dependecies for dbt-core, dbt-spark, and dbt-tests-adapter to 1.6.0rc1
Removed python 3.7 support
Fixes to be compatible with pushing limit filtering to the adapter

Updated version/changelog and dbt dependencies

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Update version  to 1.6.0rc3

---

.github/workflows/main.yml
CHANGELOG.md
dbt/adapters/databricks/__version__.py
dbt/adapters/databricks/connections.py
dbt/adapters/databricks/impl.py
dbt/include/databricks/macros/materializations/clone.sql
dev-requirements.txt
requirements.txt
setup.py
tests/functional/adapter/test_dbt_clone.py

Resolves #380
This work has been completed on the `1.6.latest` branch. Just need to sync it back to `main` before we cut our release

Bump to version 1.6 

---

.github/workflows/build_cluster_http_path.py
.github/workflows/integration.yml

Updates to new PECO-managed test environment.  Does this need a changelog entry?

Updating integration.yml for new test environment

---

CHANGELOG.md

There are no code changes in this pull request.
When I performed the merge conflict resolution for https://github.com/databricks/dbt-databricks/pull/415 I mistakenly deposited the changelog update under an already released version. This PR moves the feature reference to the correct (unreleased) version.

Fix changelog error

---

.github/workflows/build_cluster_http_path.py
.github/workflows/integration.yml
CHANGELOG.md
dbt/include/databricks/macros/python.sql
tests/integration/python/models/adding_column.py
tests/integration/python/models/basic.py
tests/integration/python/models/complex_config.py
tests/integration/python/models/models.yml
tests/integration/python/seeds/expected_merge.csv
tests/integration/python/seeds/expected_new_column.csv
tests/integration/python/test_config.py
tests/integration/python/test_on_schema_change.py
tests/integration/python/test_python_autostart.py
tests/integration/python/test_python_basic.py
tests/unit/macros/test_python_macros.py

Expands integration testing of python model config support, specifically to ensure python models work with external locations and on_schema_change.  With this PR, we should be ready for the enhanced python config support in a mainstream release.

External location testing to finalize python config support

---

dbt/adapters/databricks/__version__.py

Bump main to version 1.6.2

---

.github/CODEOWNERS
CHANGELOG.md

Two small changes here:
- Update the changelog to show the forthcoming 1.6.2 release date
- Switch around codeowners
_There are no code changes in this pull request_.

Cleanup PR: changelog and codeowners

---

.github/CODEOWNERS

No code changes in this PR. Just fixing code owners on the 1.6.latest branch.

Update code owners on 1.6.latest

---

.github/workflows/integration.yml
.github/workflows/main.yml

Updates our Github Actions files so that we don't fire expensive integration tests when I make a CHANGELOG commit.

Tests should not fire on documentation-only changes

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Updates the CHANGELOG and version to prepare for 1.6.3 release

Preparing 1.6.3 release

---

.github/workflows/integration.yml
.github/workflows/main.yml

Expanding path ignores because it seems to still trigger on CHANGELOG.md

Expanding path ignores because it seems to still trigger on CHANGELOG.md

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Preparing for the 1.6.4 release

Update to 1.6.4

---

CHANGELOG.md
dbt/include/databricks/macros/python.sql

Resolves #458 
Updates the type checking in python models to support latest DBR Dataframe types.

Fixing type funnel in python models to support latest DBRs

---

CHANGELOG.md
dbt/adapters/databricks/python_submissions.py
tests/unit/python/test_python_submissions.py

Resolves #420 
logs the databricks job run information to stdout

Log databricks job info on Python submission

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Prepares for the 1.6.5 release by updating the CHANGELOG and version

Prep for 1.6.5

---

.github/workflows/build_cluster_http_path.py
.github/workflows/integration.yml
CHANGELOG.md
dbt/adapters/databricks/__version__.py
dbt/adapters/databricks/connections.py
dbt/adapters/databricks/impl.py
dbt/adapters/databricks/python_submissions.py
requirements.txt
setup.py
tests/functional/adapter/test_grants.py
tests/functional/adapter/test_python_model.py
tests/integration/model_contract/test_model_contract.py
tests/integration/multi_catalog/test_multi_catalog.py
tests/unit/test_adapter.py

Backports several fixes from 1.6.x, and hopefully enables us to run integration tests against 1.5.x

Backport fixes from 1.6.x

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Prep for 1.6.6 release

---

CHANGELOG.md
dbt/adapters/databricks/connections.py
dev-requirements.txt
requirements.txt
setup.py
tests/unit/test_adapter.py

This is the first PR in the 1.7.x branch, with the goal of ensuring we can pass existing tests with the beta builds.  Note: I figured out what was causing my unit tests to fail, so having done that, I can probably undo the changes I made to them (it was the DatabricksCredentials object); however, that file is now factored better (to my eyes), so I'm planning to keep it.

Getting compatibility with 1.7.0

---

dbt/adapters/databricks/__version__.py

Bumps the version to prepare for release.  Changelog updated in the last PR.

1.7.0 RC release prep

---

CHANGELOG.md
tests/functional/adapter/test_date_spine.py
tests/functional/adapter/test_generate_series.py
tests/functional/adapter/test_get_intervals_between.py
tests/functional/adapter/test_get_powers_of_two.py
tests/functional/adapter/test_show.py
tests/functional/adapter/test_store_failures_as.py

Adds tests for compatibility with 1.7.0 as requested in the [adapter's guide](https://github.com/dbt-labs/dbt-core/discussions/8307)

Additional tests to ensure 1.7.0 compatibility

---

CHANGELOG.md
dbt/include/databricks/macros/materializations/seeds/helpers.sql

Resolves #476
Replication of https://github.com/databricks/dbt-databricks/pull/493 so that we can run against our infra

Faster dbt seeds

---

CHANGELOG.md

Updating CHANGELOG for 1.7.x

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

1.7.3 Release Prep

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py
dbt/adapters/databricks/connections.py
requirements.txt
setup.py

Update dbt-spark dependency and backport create_schema fix for the 1.6.latest branch

Update dbt-spark dependency and backport create_schema fix

---

requirements.txt
setup.py

Tightening the range of allowable databricks-sdk as the newer versions change the interface, leading to linting failures.

Fix Databricks sdk (0.16 messes up linting)

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py
dbt/adapters/databricks/connections.py

Update CHANGELOG and version for 1.7.4 release.  Also switching inline_params to silent since otherwise we emit a ton of warnings.

Prep for 1.7.4

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py
dbt/adapters/databricks/auth.py
dbt/adapters/databricks/connections.py
dbt/adapters/databricks/python_submissions.py
requirements.txt
setup.py

Resolves #570 
Not sure what is causing this, or why this seems to fix it, but upgrading to sdk 0.17.0 appears to fix the connection behavior while also not breaking our OAuth behavior (which 0.18.0 does).  Working on getting mypy to stop complaining, as its possible that would cause other issues if left unchecked.

Pin to databricks-sdk 0.17.0

---

dbt/adapters/databricks/impl.py
dbt/include/databricks/macros/adapters/metadata.sql
dbt/include/databricks/macros/relations/materialized_view/create.sql
dbt/include/databricks/macros/relations/materialized_view/refresh.sql
requirements.txt
setup.py
tests/functional/adapter/materialized_view_tests/test_changes.py

Preparing to release 1.8.0b2 for dbt labs testing of 1.8.0 compatibility

Prep for 1.8.0b2

---

.github/workflows/build_cluster_http_path.py
CHANGELOG.md
dbt/adapters/databricks/__version__.py
requirements.txt
setup.py

Resolves #609 
Backport the pinning of the Databricks SDK, so that we can unblock 1.6.x users

Backport: Pin Databricks SDK

---

dbt/adapters/databricks/__init__.py
dbt/adapters/databricks/auth.py
dbt/adapters/databricks/connections.py
dbt/adapters/databricks/credentials.py
dbt/adapters/databricks/python_submissions.py
tests/unit/python/test_python_submissions.py
tests/unit/test_adapter.py
tests/unit/test_auth.py
tests/unit/test_compute_config.py
tests/unit/test_idle_config.py

Since the connections file is massive and complicated, starting to refactor to chunks

Move credentials to their own file

---

CHANGELOG.md
dbt/adapters/databricks/connections.py

Resolves #582 
My understanding is that blanket changing the redirect URL will break some users, so this PR enables the user to set their own by setting `oauth_redirect_url` on their profile.

Expose oauth redirect url for user config

---

CHANGELOG.md
dbt/adapters/databricks/connections.py
dbt/adapters/databricks/credentials.py
dbt/include/databricks/macros/materializations/incremental/incremental.sql
dbt/include/databricks/macros/materializations/table.sql
dbt/include/databricks/macros/relations/tblproperties.sql
dev-requirements.txt
docs/oauth.md
requirements.txt
setup.py
tests/functional/adapter/python_model/fixtures.py
tests/functional/adapter/python_model/test_python_model.py

Forward ports fixes from 1.7.x and moves dbt dependencies to latest versions.

Prep for 2.0.0b1

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Prep for 1.7.14

---

CHANGELOG.md
dbt/adapters/databricks/auth.py
dbt/adapters/databricks/connections.py
dbt/adapters/databricks/credentials.py
dbt/adapters/databricks/events/base.py
dbt/adapters/databricks/events/connection_events.py
dbt/adapters/databricks/events/credential_events.py
dbt/adapters/databricks/events/cursor_events.py
dbt/adapters/databricks/events/other_events.py
dbt/adapters/databricks/events/pipeline_events.py
tests/functional/adapter/long_sessions/test_long_sessions.py
tests/functional/adapter/warehouse_per_model/test_warehouse_per_model.py
tests/unit/events/test_base_events.py
tests/unit/events/test_connection_events.py
tests/unit/events/test_cursor_events.py

Forward porting latest changes from 1.7.14 into 2.0.latest

Merge main 1.7.14 into 2.0.latest

---

dev-requirements.txt
requirements.txt
setup.py
tests/functional/adapter/dbt_clone/test_dbt_clone.py

Updates our 2.0.latest branch to rely on latest release candidate of upstream libraries.  I had to skip clone tests due to an upstream test bug that is waiting on a fix.

Update to 1.8.0Rc1

---

CHANGELOG.md
dbt/adapters/databricks/impl.py
dbt/adapters/databricks/relation.py
dbt/include/databricks/macros/adapters/metadata.sql
dev-requirements.txt
requirements.txt
setup.py
tests/functional/adapter/dbt_clone/test_dbt_clone.py

Metadata gathering improvements

---

.github/workflows/main.yml
dbt/adapters/databricks/__version__.py
dev-requirements.txt
requirements.txt
setup.py

Prepare for the release candidate

Prep for 2.0.0rc1

---

.github/workflows/main.yml
dbt/adapters/databricks/connections.py
dbt/adapters/databricks/events/connection_events.py
dev-requirements.txt
requirements.txt
setup.py

Fixes a logging bug and updates to latest versions
- [] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-databricks next" section.

Last minute changes for 2.0.0rc1

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py
tox.ini

Prep for 1.8.0rc1

---

CHANGELOG.md
dbt/adapters/databricks/connections.py
dbt/adapters/databricks/impl.py
dbt/adapters/databricks/utils.py
tests/unit/test_adapter.py

Replicates [629](https://github.com/databricks/dbt-databricks/pull/629) but on latest.  Also, I'm a little more aggressive about not instantiating Tables.

Lazy load agate

---

dbt/adapters/databricks/__version__.py

Prep 1.7.15

---

dbt/adapters/databricks/connections.py
dbt/adapters/databricks/events/connection_events.py

See https://github.com/databricks/dbt-databricks/pull/671 for details

Forward port fix for connection logging error to 1.8.x

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Prepare for the 1.8.0 final release

Prep for 1.8.0 release

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py
dbt/adapters/databricks/utils.py

Done from a separate branch so that I could validate changes before merging in.  After this PR, will merge the resulting 1.8.latest into main and release a 1.8.1 beta.

Merge main to 1.8.latest

---

black.ini
dbt/adapters/databricks/__version__.py
dbt/adapters/databricks/utils.py
dev-requirements.txt
requirements.txt
setup.py
tests/functional/adapter/persist_docs/test_persist_docs.py

Prepares for the 1.8.1b2 release.  Had to skip b1 because I forgot to rebase before building and pushing.

Prep for 1.8.1b2

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Prepare for the 1.8.1 release.

Prep for 1.8.1 release

---

CHANGELOG.md
tests/unit/python/test_python_submissions.py
tests/unit/test_auth.py
tests/unit/test_column.py
tests/unit/test_compute_config.py
tests/unit/test_relation.py
tests/unit/test_utils.py
tests/unit/utils.py

I've been migrating tests to be fully pytest for a while now.  This PR finishes that migration.  No more unittest.TestClass.

Migrate remaining unit tests to pytest

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Prep for 1.8.2 release

---

dbt/adapters/databricks/__version__.py

Changelog has already been updated

Updating version to 1.8.3

---

setup.py

expand dbt-spark range in setup.py

---

.github/workflows/integration.yml
CHANGELOG.md
dbt/adapters/databricks/__version__.py

Prepare for 1.8.4 release.  Also updating the integration test runner so that it doesn't kick off integration tests on these release PRs going forward.

Prep for 1.8.4 release

---

CHANGELOG.md
dbt/adapters/databricks/column.py
dbt/adapters/databricks/impl.py

Users reported that the cursor warnings were concerning, so backporting to 1.8 and to 1.7

Backport warning prevention from 1.9

---

dbt/adapters/databricks/impl.py
requirements.txt
setup.py

Update setup.py to allow for dbt-adapters ~1.3

---

tests/profiles.py

Allows ENV based configuration of auth type for running functional tests

Allow auth type to be configured for tests

---

tests/profiles.py

Allow configuring port for testing (for local docker tests)

Allow configuring port for tests

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Prep for 1.8.5 release

---

CHANGELOG.md
requirements.txt

In the 1.9 branch, test with latest PySQL

Upgrade PySql to 3.4.0

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Prep for 1.8.6 release

---

.github/workflows/integration.yml

Concurrent runs of the workflow are likely to fail and slow down both runs.  When quickly iterating, it is really annoying to have to come to Github and cancel the previous run manually.

Cancel in progress runs of the same branch

---

CHANGELOG.md
dbt/include/databricks/macros/materializations/snapshot.sql

Resolves #
#819
Do not set table properties on staging views produced as a technical artifact by the sbt snapshotting process

Fix for: https://github.com/databricks/dbt-databricks/issues/819

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Perpares for 1.8.7 release; only notable change is that we stop running cluster by None.

Prep for 1.8.7 release

---

setup.py

Pydantic pin was causing issues with dbt-core.  I'm fairly certain this is safe since I don't run setup.py when testing locally, and it's not present in requirements.txt

Remove pydantic pin

---

.github/workflows/main.yml
CHANGELOG.md
requirements.txt
setup.py

Updates to 1.9.x version of dbt-spark and 3.5.0 version of PySQL.

Update dbt-spark and pysql dependencies

---

CHANGELOG.md
dbt/adapters/databricks/api_client.py
dbt/adapters/databricks/impl.py

Refactors switching to user folder to be behind a behavior flag, since the expectation is that ultimately Shared will be deprecated.

Move use_user_folder_for_python to behavior

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Prepare for 1.9.0 final release

Prep for 1.9.0 release

---

CHANGELOG.md
pyproject.toml

Resolves #872 , #726 
Removing dependency constraints that were originally put in place to stop warnings and breaks, but are preventing customer use cases.  If this passes all of the tests, will become 1.9.1

Remove library restrictions if possible

---

tests/functional/adapter/concurrency/test_concurrency.py

The test in question verifies log output, but that output varies depending on versions of libraries installed.  As such, I've removed the part that varies.

Fix failing concurrency test

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py
dbt/adapters/databricks/relation_configs/tblproperties.py
tests/functional/adapter/materialized_view_tests/test_changes.py

Prep for 1.9.1 release

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Prepping to release first thing Tuesday

Prep for 1.9.2 release

---

pyproject.toml

dbt Labs consolidated to a monorepo, which broke the dev paths.

Attempt to fix git paths

---

CHANGELOG.md
dbt/adapters/databricks/impl.py
tests/functional/adapter/iceberg/test_iceberg_support.py
tests/functional/adapter/simple_snapshot/test_snapshot.py

Resolves #918 
After investigation, the only blocker here was one I put in place.  The underlying logic is the same, so just need to unblock.  Also reactivating iceberg tests now that they are working in prod again.

Unblocking iceberg snapshots, reactivating iceberg tests

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py
pyproject.toml

Prep for 1.9.5 release

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py

Prep for 1.9.6 release

---

CHANGELOG.md
dbt/adapters/databricks/connections.py
dbt/include/databricks/macros/adapters/python.sql
dbt/include/databricks/macros/adapters/relation.sql
dbt/include/databricks/macros/materializations/incremental/incremental.sql
dbt/include/databricks/macros/materializations/incremental/strategies.sql
dbt/include/databricks/macros/relations/create_backup.sql
dbt/include/databricks/macros/relations/file_format.sql
dbt/include/databricks/macros/relations/table/create.sql
docs/incremental_flow.md
tests/functional/adapter/basic/test_incremental_v2.py
tests/functional/adapter/constraints/fixtures.py
tests/functional/adapter/constraints/test_constraints.py
tests/functional/adapter/constraints/test_constraints_v2.py
tests/functional/adapter/incremental/test_incremental_on_schema_change.py
tests/functional/adapter/incremental/test_incremental_predicates.py
tests/functional/adapter/incremental/test_incremental_unique_id.py
tests/functional/adapter/incremental/test_merge_exclude_columns.py
tests/functional/adapter/microbatch/test_microbatch.py
tests/functional/adapter/python_model/test_python_model.py

First attempt at rewriting incremental materializations to use the Materialization V2 approach (create then insert, as opposed to CTAS)

Incremental V2

---

CHANGELOG.md
dbt/adapters/databricks/__version__.py
dbt/adapters/databricks/connections.py

Realized by inspection today that I was missing an important query_header_context spot in my refactor PR.  Quick fix.

Readded missed language field for connections

---

dbt/include/databricks/macros/adapters/metadata.sql

dbt Labs brought to my attention that I had this still hanging around in main

Remove dangling code

---

CHANGELOG.md
tests/functional/adapter/sample_mode/test_sample_mode.py

In dbt 1.10.0, dbt Labs is introducing sample mode.  This PR adds a functional test to ensure it works with Databricks.

Adding test for sample mode

---

CHANGELOG.md
pyproject.toml

With 1.10.0, upgrading to v4 of PySQL

Upgrade to V4 of Databricks Sql Connector

---

dbt/adapters/databricks/credentials.py
dbt/adapters/databricks/handle.py
dbt/adapters/databricks/relation.py
dbt/include/databricks/macros/adapters/catalog.sql
dbt/include/databricks/macros/adapters/columns.sql
tests/unit/macros/adapters/test_catalog_macros.py
tests/unit/macros/adapters/test_columns_macros.py
tests/unit/macros/base.py
tests/unit/macros/relations/test_constraint_macros.py
tests/unit/macros/relations/test_optimize_macros.py
tests/unit/macros/relations/test_query_macros.py
tests/unit/macros/relations/test_table_macros.py
tests/unit/macros/relations/test_tags_macros.py
tests/unit/macros/relations/test_view_macros.py

Using copilot to help me troubleshoot the very annoying to write macro tests, but I did discover some bugs while doing it.  Will need to chip away at this over time.  A few other minor fixes that I will comment on in the PR.

Adding more macro unit tests, cleaning up some macros

---

pyproject.toml

Saw this morning that there was a new SDK release, and it looks like it may improve U2M experience, so upping the versions to allow it, assuming tests pass.

Trying 0.47.0 of the sdk

---

dbt/include/databricks/macros/materializations/incremental/incremental.sql
dbt/include/databricks/macros/materializations/table.sql
tests/functional/adapter/constraints/test_constraints_v2.py

A user brought to my attention that the safer operations will increase storage costs, so ensuring false as the default (which is closer to how we do things in 1.9.0).

Default to false for 'use_safer_relation_operations'

---

dbt/include/databricks/macros/adapters/catalog.sql
dbt/include/databricks/macros/adapters/columns.sql
dbt/include/databricks/macros/adapters/copy_into.sql
dbt/include/databricks/macros/adapters/databricks_catalog.sql
dbt/include/databricks/macros/adapters/metadata.sql
dbt/include/databricks/macros/adapters/persist_docs.sql
dbt/include/databricks/macros/etc/statement.sql
tests/unit/macros/adapters/test_catalog_macros.py
tests/unit/macros/adapters/test_metadata_macros.py
tests/unit/macros/adapters/test_persist_docs_macros.py

Further macro testing, and minor macro refactoring to make things easier to test.

More macro cleanup and unit tests

---

CHANGELOG.md

Had to hold 1.10.1 to fix other issues, so updating release date.

Fixing changelog for 1.10.1 release date

---

CHANGELOG.md
dbt/adapters/databricks/constraints.py
pyproject.toml
tests/unit/test_constraints.py

Resolves #1007 
Apparently using multiple not null constraints was not working.

Fix multiple null constraint situation

---

tests/functional/adapter/simple_snapshot/test_new_record_mode.py

Resolves breaking change from https://github.com/dbt-labs/dbt-adapters/commit/d8ebe134ce0ea58738f257487544e672e456916c. The filename and structure of test fixtures were updated which results in a breaking change for a dbt-databricks test 
Minor fix to import the correct references and process fixtures correctly

Fix broken test_snapshot_new_record_mode

---

CHANGELOG.md
dbt/adapters/databricks/constraints.py
dbt/adapters/databricks/impl.py
dbt/adapters/databricks/relation_configs/constraints.py
dbt/adapters/databricks/relation_configs/incremental.py
dbt/include/databricks/macros/relations/components/constraints.sql
dbt/include/databricks/macros/relations/table/alter.sql
tests/functional/adapter/incremental/fixtures.py
tests/functional/adapter/incremental/test_incremental_constraints.py
tests/unit/relation_configs/test_constraint.py
tests/unit/relation_configs/test_incremental_config.py

Resolves constraint part of #982. Does not resolve the contract enforcement 
Support constraints for incremental materializations. Databricks supports the following 4 constraints based on https://docs.databricks.com/aws/en/tables/constraints
- Non-null (enforced, requires UC)
- Check (enforced, does not require UC)
- Primary key (not enforced, requires UC)
- Foreign key (not enforced, requires UC)

Constraints for incremental materialization

---

CHANGELOG.md
dbt/include/databricks/macros/relations/view/alter.sql

Fix alter view dispatch

---

tests/functional/adapter/incremental/test_incremental_constraints.py

Fix non-deterministic test from result set ordering

---

.github/workflows/coverage.yml
.github/workflows/main.yml
.gitignore
pyproject.toml

Resolves #
Add test coverage statistics to PRs by using https://github.com/py-cov-action/python-coverage-comment-action. No minimum coverage % enforced at this point, just for informational purposes

Add unit test coverage report to pre-merge

---

tests/functional/adapter/column_masks/fixtures.py
tests/functional/adapter/column_masks/test_column_mask.py

Add basic happy path coverage for streaming table column masks (missed in a previous PR)

Add test coverage for streaming table column mask

---

docs/dbt-databricks-dev.md

Working with Cursor to expand the development documentation.  This is the first expansion of the dev docs.

Improving dev docs

---

docs/dbt-databricks-dev.md
docs/testing.md

Explains testing, including patterns, how-tos, standards, etc.

Adding a fairly comprehensive testing doc

---

AGENTS.md

Adds AGENTS.md to improve developing this project with AI

chore: Adding AGENTS.md

---

.github/workflows/integration.yml
.github/workflows/main.yml
CHANGELOG.md
pyproject.toml

Hoping to improve install experience as well as test latest versions

chore: Updating dependencies and using uv

---

CHANGELOG.md
dbt/adapters/databricks/relation_configs/materialized_view.py
dbt/adapters/databricks/relation_configs/streaming_table.py
dbt/include/databricks/macros/relations/materialized_view/create.sql
dbt/include/databricks/macros/relations/streaming_table/create.sql
tests/functional/adapter/materialized_view_tests/fixtures.py
tests/functional/adapter/materialized_view_tests/test_basic.py
tests/functional/adapter/streaming_tables/fixtures.py
tests/functional/adapter/streaming_tables/test_st_basic.py
tests/unit/relation_configs/test_materialized_view_config.py
tests/unit/relation_configs/test_streaming_table_config.py

Migrated from https://github.com/databricks/dbt-databricks/pull/1101 to add tests

feat: MV/ ST Liquid Clustering
