databricks/dbt-databricks

dbt/adapters/databricks/connections.py
resolves #34
Closes the connection properly.
=> Close the connection properly

dbt/adapters/databricks/__init__.py, requirements.txt, setup.py
Resolves #32
Fixes dbt-labs/spark-utils#23
Integration tests will be added to dbt-labs/spark_utils to ensure compatibility with dbt-databricks.
Inherit from dbt-spark in order to maintain compatibility with existing spark-utils and other macros.
- [ x] I have run this code in development and it appears to resolve the stated issue
=> Inherit from dbt-spark for backward compatibility

tests/integration/base.py, tests/integration/conftest.py, tests/specs/spark-databricks-sql-endpoint-connector.dbtspec, tox.ini
Adds a new test profile and env variable DBT_DATABRICKS_ENDPOINT_HTTP_PATH
Some features behave differently on sql endpoints vs spark clusters.
=> Add SQL Endpoint specific integration tests.

.github/workflows/main.yml, tests/integration/base.py, tests/integration/conftest.py, tests/integration/get_columns_in_relation/test_get_columns_in_relation.py, tests/integration/incremental_on_schema_change/test_incremental_on_schema_change.py, tests/integration/incremental_strategies/test_incremental_strategies.py, tests/integration/persist_docs/test_persist_docs.py, tests/integration/seed_column_types/test_seed_column_types.py, tests/integration/store_failures/test_store_failures.py, tests/specs/databricks-cluster.dbtspec, tests/specs/databricks-sql-endpoint.dbtspec, tox.ini
Enables custom integration tests for SQL Endpoint and refines integration tests.
- Enable custom integration tests for SQL Endpoint
- Rename the tox env name for integration tests:
- For the all purpose cluster: `integration-spark-databricks-sql-connector` -> `integration-databricks-cluster`
- For the SQL Endpoint: `integration-spark-databricks-sql-endpoint-connector` -> `integration-databricks-sql-endpoint`
- Rename the environment variable name `DBT_DATABRICKS_HTTP_PATH` to `DBT_DATABRICKS_CLUSTER_HTTP_PATH`
After this, we need to setup environment variable for integration tests:
```
export DBT_DATABRICKS_HOST_NAME='<server-hostname>'
export DBT_DATABRICKS_CLUSTER_HTTP_PATH='<http-path> for the all purpose cluster'
export DBT_DATABRICKS_ENDPOINT_HTTP_PATH='<http-path> for the SQL …
```
=> Enable custom integration tests for SQL Endpoint and refine integration tests.

.github/workflows/main.yml, black.ini, dbt/adapters/databricks/__init__.py, dbt/adapters/databricks/__version__.py, dbt/adapters/databricks/column.py, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/relation.py, dbt/include/databricks/__init__.py, dev_requirements.txt, mypy.ini, tox.ini
Setups linter checks.
- `mypy` check and fix the type hint errors.
- `black` check and apply black formatter.
To run linter:
```
tox -e linter
```
To apply black formatter:
```
tox -e black
```
=> Setup linter checks.

dbt/adapters/databricks/connections.py, dbt/adapters/databricks/impl.py, mypy.ini, requirements.txt, setup.py
Bumps up databricks-sql-connector to `1.0.1` and use the Cursor APIs.
- `Cursor.schemas()` to retrieve a list of schemas.
=> Bump up databricks-sql-connector to 1.0.1 and use the Cursor APIs.

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/adapters.sql, dbt/include/databricks/macros/materializations/incremental/strategies.sql, dbt/include/databricks/macros/materializations/seed.sql, tests/integration/set_tblproperties/models/set_tblproperties.sql, tests/integration/set_tblproperties/models/set_tblproperties_to_view.sql, tests/integration/set_tblproperties/seeds/expected.csv, tests/integration/set_tblproperties/test_set_tblproperties.py, tests/unit/test_macros.py
resolves #33
Supports to set `tblproperties` when creating tables and views.
In the models config, set `tblproperties` as follows.
```
{{ config(
materialized='incremental', 
tblproperties={
'delta.autoOptimize.optimizeWrite' : 'true',
'delta.autoOptimize.autoCompact' : 'true'
}
) }}
```
=> Support for setting table properties as part of a model configuration

tests/integration/base.py, tests/integration/conftest.py, tests/integration/current_catalog/models/current_catalog.sql, tests/integration/current_catalog/models/expected.sql, tests/integration/current_catalog/seeds/expected.csv, tests/integration/current_catalog/test_current_catalog.py, tests/integration/get_columns_in_relation/test_get_columns_in_relation.py, tests/integration/incremental_on_schema_change/test_incremental_on_schema_change.py, tests/integration/incremental_strategies/test_incremental_strategies.py, tests/integration/persist_docs/test_persist_docs.py, tests/integration/seed_column_types/test_seed_column_types.py, tests/integration/set_tblproperties/test_set_tblproperties.py, tests/integration/store_failures/test_store_failures.py, tests/specs/databricks-cluster.dbtspec, tests/specs/databricks-sql-endpoint.dbtspec, tests/specs/databricks-uc-cluster.dbtspec, tests/specs/databricks-uc-sql-endpoint.dbtspec, tox.ini
Adds integration test profiles against UC clusters.
The http-path should be set by environment variables:
- `DBT_DATABRICKS_UC_CLUSTER_HTTP_PATH`
- `DBT_DATABRICKS_UC_ENDPOINT_HTTP_PATH`
The initial catalog can be set by:
- `DBT_DATABRICKS_UC_INITIAL_CATALOG`
or "main" if not exist.
To run the tests:
- `tox -e integration-databricks-uc-cluster`
- `tox -e integration-databricks-uc-sql-endpoint`
=> Add integration test profiles against UC clusters.

tox.ini
Makes tox integration tests take additional arguments for `pytest` command.
For example:
```
tox -e integration-databricks-sql-endpoint -- -k test_dbt_empty
```
=> Make tox integration tests take additional arguments for pytest command.

black.ini, dev_requirements.txt
The `black` command fails due to the dependency issue https://github.com/psf/black/issues/2964.
Upgrades `black` to `22.3.0`.
=> Upgrade black to 22.3.0

dbt/adapters/databricks/connections.py
Adds `database` and `schema` in the log when executing schemas API.
For example, in `dbt.log`:
```
... [debug] [ThreadPool]: On list_schemas: GetSchemas(database=None, schema=None)
```
=> Add database and schema in the log when executing schemas API.

tests/functional/adapter/test_basic.py
Adds `TestBaseAdapterMethodDatabricks` that is a port from https://github.com/dbt-labs/dbt-spark/pull/328.
=> Add TestBaseAdapterMethodDatabricks.

requirements.txt, setup.py
Sets the upper bound on `databricks-sql-connector`.
`databricks-sql-connector 2.0.0` has been released, but it has a dependency issue.
=> Set the upper bound on databricks-sql-connector.

dbt/adapters/databricks/connections.py
Shows full error info in debug log for `databricks-sql-connector 2.0`.
The way to hold error info was changed in `databricks-sql-connector 2.0`.
We should show the full error info in the debug log.
=> Show full error info in debug log for databricks-sql-connector 2.0

tests/integration/persist_constraints/test_persist_constraints.py
This PR fixes two Delta constraint test failures when running with DBR 9.1 LTS.
=> Fix Delta constraint tests for DBR 9.1 LTS

tests/integration/base.py
Fixes `DBTIntegrationTest` to be more robust.
- Make `DBTIntegrationTest.prefix` `@property` to not share the same prefix in sub classes.
- Drop the schema with the suffix `_dbt_test__audit` created when `dbt test --store-failures` is run.
=> Fix DBTIntegrationTest to be more robust

dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/materializations/snapshot.sql, dbt/include/databricks/macros/statement.sql, tests/integration/persist_constraints/test_persist_constraints.py
We introduced Delta constraints at #71 and now that snapshot query could fail when it's violating the constraints.
In that case, the temporary view keeps existing because snapshot uses a permanent view and drop it later.
We should always drop them.
=> Fix snapshot to always drop the staging table

dbt/adapters/databricks/connections.py
Uses `packaging.version` instead of `distutils.version` to suppress warnings.
```
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```
`package` module is safe to use as it's included in the `dbt-core`'s dependencies.
https://github.com/dbt-labs/dbt-core/blob/e50678c91424142aa1a4995ee1d358dac6a6fdf8/core/setup.py#L65
=> Use packaging.version instead of distutils.version

CHANGELOG.md, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/relation.py, dbt/adapters/databricks/utils.py, tests/unit/test_relation.py
Backport of #98 
Blocks taking `jinja2.runtime.Undefined` into `DatabricksAdapter`.
When calling the adapter method from macros, `jinja2.runtime.Undefined` can be passed to `DatabricksAdapter` that could cause unexpected behavior.
For example,
https://github.com/databricks/dbt-databricks/blob/b8152b697b003e02fb52e86f59b2bde4b492cc0a/dbt/include/databricks/macros/materializations/snapshot.sql#L33
The `model.database` is not defined and `jinja2.runtime.Undefined` will be used to call `adapter.check_schema_exists` and `Cursor.schema()` will fail:
```
[debug] [Thread-13 ]: Databricks adapter: Error while running:
GetSchemas(database=, schema=test16533281379208408401_test_basic)
[debug] [Thread-13 ]: Databricks adapter: <class 'databricks.sql.exc.RequestError'>: Error during request to server …
```
=> [1.1] Block taking jinja2.runtime.Undefined into DatabricksAdapter.

dbt/adapters/databricks/connections.py, tests/unit/test_adapter.py
Fixes the user agent entry to avoid nested parens.
The full user agent was like `PyDatabricksSqlConnector/2.0.2 (dbt-databricks/1.2.0 (dbt-cloud))`, but we should avoid nested parens.
The full user agent after the fix will be like `PyDatabricksSqlConnector/2.0.2 (dbt-databricks/1.2.0; dbt-cloud)`.
=> Fix the user agent entry to avoid nested parens.

dbt/include/databricks/profile_template.yml
Adds setting of UC to the project template:
- When using UC:
```
$ dbt init
...
[1] use Unity Catalog
[2] not use Unity Catalog
Desired unity catalog option (enter a number): 1
catalog (initial catalog): cat
...
```
- When not using UC:
```
$ dbt init
...
[1] use Unity Catalog
[2] not use Unity Catalog
Desired unity catalog option (enter a number): 2
...
```
=> Add setting of UC to the project template

CHANGELOG.md, dbt/include/databricks/macros/materializations/incremental/incremental.sql
Ports the upstream change: Not dropping table for incremental full refresh with delta (https://github.com/dbt-labs/dbt-spark/issues/287)
=> Port: Not dropping table for incremental full refresh with delta

tests/conftest.py, tests/functional/adapter/utils/fixture_listagg.py, tests/functional/adapter/utils/test_utils.py
Ports tests for lift + shift for cross-db macros from [dbt-labs/dbt-spark#359](https://github.com/dbt-labs/dbt-spark/pull/359).
=> Port tests for lift + shift for cross-db macros from dbt-spark

CHANGELOG.md, dbt/adapters/databricks/connections.py, tests/unit/test_adapter.py
Adds `connection_parameters` as part of credential for `databricks-sql-connector` connection parameters.
This can be used to customize the connection by setting additional parameters.
The full parameters are listed at [Databricks SQL Connector for Python](https://docs.databricks.com/dev-tools/python-sql-connector.html#connect-method).
Currently, the following parameters are reserved for `dbt-databricks`.
- server_hostname
- http_path
- access_token
- session_configuration
- catalog
- schema
=> Add connection_parameters for databricks-sql-connector connection parameters

dbt/include/databricks/macros/materializations/incremental/incremental.sql
Avoids using default as a temporary fix for dbt-labs/dbt-core#5359.
This is a temporary fix and dbt-labs/dbt-spark#394 should be ported later.
=> Avoid using default as a temporary fix for dbt-labs/dbt-core#5359.

dbt/adapters/databricks/connections.py
Refines `DatabricksCredentials._connection_keys` to show only meaningful configs.
Currently `dbt debug` shows always shows `host`, `http_path`, `database`, `schema`, and `session_properties`, but we should show only meaningful configs.
Also use `catalog` instead of `database` for the catalog config name:
For example:
```
$ dbt debug
...
Connection:
host: your.databrickshost.com
http_path: /sql/your/http/path
schema: schema_name
...
```
If `catalog` is set:
```
$ dbt debug
...
Connection:
host: your.databrickshost.com
http_path: /sql/your/http/path
catalog: catalog_name
schema: schema_name
...
```
=> Refine DatabricksCredentials._connection_keys to show only meaningful configs

requirements.txt, setup.py
Upgrades the lower bound for `databricks-sql-connector` to `2.0.2`.
=> Upgrade the lower bound for databricks-sql-connector

dbt/adapters/databricks/connections.py
Fixes `DatabricksCredentials._connection_keys`.
- `catalog` can't be used; should use `database`
- `database` can't be removed.
Otherwise, `Undefined` object comes from somewhere:
```
TypeError: can not serialize 'Undefined' object
```
=> Fix DatabricksCredentials._connection_keys

tests/integration/persist_docs/test_persist_docs.py
Fixes `TestPersistDocsDelta` to use `{database_schema}`.
=> nit: Fix TestPersistDocsDelta to use `{database_schema}`

dbt/adapters/databricks/connections.py, tests/integration/debug/test_debug.py
Retry: `DatabricksCredentials._connection_keys` to show only meaningful configs (#138).
Assuming `DatabricksCredentials.connection_info(self, *, with_aliases: bool = False)` is called from only:
- `Profile` with `with_aliases=True`
- `DebugTask` without `with_aliases` (`False` by default)
Thus, if `with_aliases` is `True`, `DatabricksCredentials._connection_keys` should return the same tuple as the current one for the internal use; otherwise it can use `catalog` to show in the debug output.
=> Retry DatabricksCredentials._connection_keys to show only meaningful configs

.github/workflows/main.yml, setup.py
The dependent library `databricks-sql-connector` doesn't support Python 3.10 yet (databricks/databricks-sql-python#26).
We should also avoid incompatible Python version.
=> Set upper bound for Python

CHANGELOG.md, README.md, requirements.txt, setup.py
Set upper bound for `databricks-sql-connector` when Python 3.10 instead of `Python`.
Note that `databricks-sql-connector` doesn't support Python 3.10 yet, so `dbt-databricks` doesn't either.
=> Set upper bound for databricks-sql-connector instead of Python

CHANGELOG.md, README.md, dbt/adapters/databricks/connections.py, requirements.txt, setup.py, tests/unit/test_adapter.py
Backports two commits to `1.1.latest`.
- Set upper bound for databricks-sql-connector instead of Python (#154)
- Include the value of environment variable "DBT_DATABRICKS_INVOCATION_ENV" to the user agent entry. (#155)
=> Backports to 1.1.latest

.github/workflows/main.yml, CHANGELOG.md, README.md, requirements.txt, setup.py
Supports Python 3.10.
[`databricks-sql-connector 2.0.4`](https://pypi.org/project/databricks-sql-connector/2.0.4/) has been released with [Python 3.10 support](https://github.com/databricks/databricks-sql-python/issues/26).
=> Support Python 3.10

dbt/include/databricks/macros/materializations/seed.sql
resolves #114
Uses `insert overwrite` for the first batch of seed to help seeds in external tables.
This must be a temporary fix and should follow dbt-labs/dbt-spark#182.
=> Use insert overwrite for the first batch of seed

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/materializations/incremental/incremental.sql, dbt/include/databricks/macros/materializations/incremental/strategies.sql
Applies "Initial refactoring of incremental materialization" (dbt-labs/dbt-core#5359).
Now it uses `adapter.get_incremental_strategy_macro` instead of dbt-spark's `dbt_spark_get_incremental_sql` macro to dispatch the incremental strategy macro. The overwritten `dbt_spark_get_incremental_sql` macro will not work anymore.
=> Apply "Initial refactoring of incremental materialization"

CHANGELOG.md, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/materializations/seed.sql, tests/integration/base.py
Explicitly closes cursors.
Sometimes we observe **Query has been timed out due to inactivity** error in the Query History UI, that is likely because the cursors are not closed.
=> Explicitly close cursors

CHANGELOG.md, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/materializations/seed.sql, tests/integration/base.py
Backports two commits to `1.2.latest`.
- Use insert overwrite for the first batch of seed (#149)
- Explicitly close cursors (#163)
=> Backports to 1.2.latest

CHANGELOG.md, requirements.txt, setup.py
Upgrades `databricks-sql-connector` to `2.0.5`.
=> Upgrade databricks-sql-connector to 2.0.5

CHANGELOG.md, dbt/adapters/databricks/connections.py
Embeds `dbt-databricks` and `databricks-sql-connector` versions to SQL comments.
=> Embed dbt-databricks and databricks-sql-connector versions to SQL comments

CHANGELOG.md, dbt/adapters/databricks/connections.py, tests/integration/fail_fast/models/schema.yml, tests/integration/fail_fast/models/view_model.sql, tests/integration/fail_fast/test_fail_fast.py
`DatabricksSQLConnectionWrapper` should have `cancel` method and handle it properly.
Otherwise, the following error will be seen when cancelling the session due to e.g., `dbt test --fail-fast`:
```
AttributeError: 'DatabricksSQLConnectionWrapper' object has no attribute 'cancel'
```
=> Fix cancellation.

.github/workflows/stale.yml
Disables auto-closing issues/PRs.
The `Stale` label will still be added after 180 days with no activity.
=> Disable auto-closing issues/PRs.

CHANGELOG.md, dbt/adapters/databricks/connections.py, tests/unit/test_adapter.py
Currently there is no way to specify `http_headers` in `connection_parameters` properly.
`http_headers` should be `dict` in the profile:
```yml
...
connection_parameters:
http_headers:
aaa: xxx
bbb: yyy
...
```
but previously it failed to connect to the cluster.
```
failed to connect: unsupported operand type(s) for +: 'dict' and 'list'
```
=> http_headers should be dict in the profile.

dbt/include/databricks/macros/materializations/incremental/strategies.sql
Removes duplicated macros that became unnecessary after the `dbt-spark` change at dbt-labs/dbt-spark#445.
=> Remove unnecessary duplicated macros.

dbt/adapters/databricks/connections.py
Manages cursors to avoid relying on the protected member.
=> Manage cursors to avoid relying on the protected member.

CHANGELOG.md, tests/functional/adapter/utils/test_data_types.py
Adds a test for `type_boolean` macro introduced at dbt-labs/dbt-core#5739, following dbt-labs/dbt-spark#471.
=> Add a test for `type_boolean` macro

CHANGELOG.md, dbt/include/databricks/macros/copy_into.sql, tests/integration/copy_into/models/expected_target.sql, tests/integration/copy_into/models/schema.yml, tests/integration/copy_into/models/source.sql, tests/integration/copy_into/models/target.sql, tests/integration/copy_into/test_copy_into.py
resolves #41
This PR adds a macro `databricks_copy_into` to support the [COPY INTO](https://docs.databricks.com/spark/latest/spark-sql/language-manual/delta-copy-into.html) command. You can use it with dbt run-operation:
```bash
dbt run-operation databricks_copy_into --args ...
```
=> Support for COPY INTO

dbt/adapters/databricks/connections.py
Uses `search` instead of `match` to extract DBR version because `match` is sometimes too strict.
=> Use search instead of match to extract DBR version.

tests/functional/adapter/test_ephemeral.py
Avoids comparing the query itself because the table names are different between non-UC and UC tests.
=> Avoid comparing the query itself.

dbt/adapters/databricks/connections.py
Fixes linter errors caused by [upstream changes](https://github.com/dbt-labs/dbt-core/pull/5954).
```
dbt/adapters/databricks/connections.py:440: error: Argument "conn_name" to "ConnectionUsed" has incompatible type "Optional[str]"; expected "str"  [arg-type]
dbt/adapters/databricks/connections.py:449: error: Argument "conn_name" to "SQLQuery" has incompatible type "Optional[str]"; expected "str"  [arg-type]
dbt/adapters/databricks/connections.py:491: error: Argument "conn_name" to "ConnectionUsed" has incompatible type "Optional[str]"; expected "str"  [arg-type]
dbt/adapters/databricks/connections.py:496: error: Argument "conn_name" to "SQLQuery" has incompatible type "Optional[str]"; expected "str"  [arg-type]
```
=> Fix linter errors caused by upstream changes.

CHANGELOG.md, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/impl.py
Shows and logs a warning when schema contains `'.'`.
As a side work, trying to help more cases where schema contains `'.'` in `list_relations_without_caching`.
=> Show and log a warning when schema contains '.'.

dbt/adapters/databricks/connections.py, tests/unit/test_adapter.py
Before a header like `{'string': 'some-string'}` would result in the header: `{'string': '"some-string"'}`. This PR fixes this and returns the correct header `{'string': 'some-string'}`.
=> Fix double quoting strings in HTTP headers

CHANGELOG.md, dbt/adapters/databricks/connections.py
Raises an exception when schema contains `'.'`.
This is a breaking change since `1.4.0` to disallow a workaround using `schema` to set a catalog for the older versions.
=> Raise an exception when schema contains '.'.

CHANGELOG.md, dbt/include/databricks/macros/copy_into.sql, tests/integration/copy_into/models/expected_target_with_expression_list.sql, tests/integration/copy_into/models/target_with_expression_list.sql, tests/integration/copy_into/test_copy_into.py
Fixes copy into macro when passing `expression_list`.
```
Encountered an error while running operation: Runtime Error
Runtime Error
[PARSE_SYNTAX_ERROR] Syntax error at or near 'select'(line 5, pos 9)
== SQL ==
/* ... */
copy into test16673467754364144015_copy_into.target_with_expression_list
from select id, name from '/path/to/source'
---------^^^
fileformat = parquet
format_options ('mergeSchema' = 'true')
copy_options ('mergeSchema' = 'true')
```
There should be parenthesis surrounding `select id, name from '/path/to/source'`.
=> Fix copy into macro when passing expression_list.

CHANGELOG.md, dbt/adapters/databricks/impl.py
Partially reverts #221 to fix the case where `schema` config contains uppercase letters.
```
Compilation Error in model test (models/test.sql)
When searching for a relation, dbt found an approximate match. Instead of guessing
which relation to use, dbt will move on. Please delete DBT_TEST.test, or rename it to be less ambiguous.
Searched for: dbt_test.test
Found: DBT_TEST.test
> in macro load_cached_relation (macros/adapters/relation.sql)
> called by macro load_relation (macros/adapters/relation.sql)
> called by macro materialization_incremental_databricks (macros/materializations/incremental/incremental.sql)
> called by model test (models/test.sql)
```
=> Partially revert to fix the case where schema config contains uppercase letters.

dbt/adapters/databricks/connections.py, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/relation.py, dbt/include/databricks/macros/adapters.sql, dbt/include/databricks/macros/materializations/incremental/incremental.sql, dbt/include/databricks/macros/materializations/snapshot.sql, dbt/include/databricks/macros/materializations/table.sql, tests/functional/adapter/test_basic.py, tests/unit/test_adapter.py
Avoids show table extended command.
This is based on dbt-labs/dbt-spark#433.
1. Create a table/view list with `show tables in {{ relation }}` and `show views in {{ relation }}` commands, or `get_tables` API when `catalog` is provided.
2. Retrieve additional information by `describe extended {{ relation }}` command.
1. `get_relation` with `needs_information=True`
2. `get_columns_in_relation`
=> Avoid show table extended command.

CHANGELOG.md, dbt/adapters/databricks/column.py, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/adapters.sql, tests/unit/test_adapter.py
Uses `show table extended` with table name list for `get_catalog`.
- Running `describe table extended` for all tables could be slower than `show table extended` with table name list.
- Statistics that will appear in the generated docs are not included in `describe table extended`.
=> Use show table extended with table name list for get_catalog.

CHANGELOG.md, dbt/adapters/databricks/connections.py
Applies connection retry refactor, add defaults with exponential backoff as per an item from #127.
- Refactors retry logic to use `retry_connection` from core.
- Adds consistent defaults with other adpaters:
- if `connect_retries` and `connect_timeout` are not specified: 1 retry after 1s
- if `connect_retries` is specified but `connect_timeout` is not, it will use exponential backoff
=> Apply connection retry refactor, add defaults with exponential backoff

.gitignore, CHANGELOG.md, dbt/adapters/databricks/relation.py, tests/unit/test_macros.py, tests/unit/test_relation.py
When working with the Unity Catalog, it is very convenient to quote catalog, schema, or identifiers so generated catalog and schema names work without extra configuration.  
resolves #240
=> Enable quotes by default

tests/functional/adapter/utils/test_utils.py
Follows up on adding `escape_single_quotes` macro.
- dbt-labs/dbt-spark#573
=> Follow up on adding escape_single_quotes macro.

CHANGELOG.md, dbt/include/databricks/macros/copy_into.sql
This PR adds an optional key word argument to the `databricks_copy_into` macro that allows the user to specify a pattern for file globbing. Please let me know if there are unintended consequences i'm not considering but based on my reading of the docs this should work. Please let me know how you normally handle unit testing.
=> Add optional argument for glob pattern in databricks COPY INTO

dbt/adapters/databricks/impl.py
Fixes linter errors caused by the upstream changes https://github.com/dbt-labs/dbt-core/commit/17014bfad3e204279c94c6a0285f784fc10711eb.
```
dbt/adapters/databricks/impl.py:144: error: "AttrDict" has no attribute "select"  [attr-defined]
dbt/adapters/databricks/impl.py:163: error: Incompatible types in assignment (expression has type "List[<nothing>]", variable has type "AttrDict")  [assignment]
dbt/adapters/databricks/impl.py:167: error: Incompatible types in assignment (expression has type "List[<nothing>]", variable has type "AttrDict")  [assignment]
dbt/adapters/databricks/impl.py:214: error: "AttrDict" has no attribute "columns"  [attr-defined]
dbt/adapters/databricks/impl.py:290: error: Argument 2 to "parse_describe_extended" of "DatabricksAdapter" has incompatible type "AttrDict"; …
```
=> Fix linter errors.

dbt/adapters/databricks/relation.py, tests/unit/test_relation.py
If an user has a model name such as models/mf/sf/TNAME.sql, the second dbt run will fail with:
```
When searching for a relation, dbt found an approximate match. Instead of guessing 
12:24:19    which relation to use, dbt will move on. Please delete `cname`.`sname`.`tname`, or rename it to be less ambiguous.
12:24:19    Searched for: `cname`.`sname`.`TNAME`
12:24:19    Found: `cname`.`sname`.`tname`
12:24:19    
12:24:19    > in macro materialization_incremental_databricks (macros/materializations/incremental/incremental.sql)
12:24:19    > called by model TNAME (models/mf/sf/TNAME.sql)
```
This PR overwrites the relation.matches method and removes case sensitive checks.
=> Ignore case sensitivity in relation matches method

.github/CODEOWNERS, dbt/adapters/databricks/__version__.py, dev-requirements.txt, requirements.txt, setup.py, tox.ini
Given changes from 1.4 to 1.5 in dbt, we need to be able to maintain specific dependency versions in order to run tests
=> Specific dbt dependencies

tests/functional/adapter/test_grants.py
Fixes `test_grants` to use the error class to check the error.
There was a change on the error message when the specified privilege doesn't exist.
We should use the error class `INVALID_PARAMETER_VALUE` that is contained in the error message and more stable.
=> Fix test_grants to use the error class to check the error.

dbt/adapters/databricks/impl.py
Because of a [AWS Glue issue](https://github.com/dbt-labs/dbt-spark/pull/54), it was set to handle any exception and returning empty list of tables. The problem is that further logic decides to create or replace table, which leads to table being overwritten and all previous partitions are lost.
I believe that the problem the previous fix solves is no where near as important to Databricks, and the problem it causes is very bad.
resolves #266
=> Raise exception on unexpected error of list relations

dbt/adapters/databricks/impl.py, tests/unit/test_adapter.py
resolves #277 
When not using Unity Catalog, and on an older DBR version, we were matching the wrong error message.
`Database `foo` not found` was expected but we got ```Database '`foo`' not found```
I moved the code checking the message into its own function and added some unit tests.
=> fix database not found error matching

dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/adapters.sql, dbt/include/databricks/macros/materializations/incremental/incremental.sql, dbt/include/databricks/macros/materializations/table.sql, tests/integration/zorder/models/multiple_zorder_model.sql, tests/integration/zorder/models/single_zorder_model.sql, tests/integration/zorder/test_zorder.py, tests/unit/test_macros.py
Resolves #122
This PR augments the dbt model config with:
```python
config(
materialized='incremental',
zorder="column_A" | ["column_A", "column_B"]
)
```
Under the hood, after every model with zorder is build (initial or incremental), we'll run a `OPTIMIZE relation ZORDER BY ()` statement.
A var is available to skip OPTIMIZE if necessary: `databricks_skip_optimize`
One can set it in the `dbt-project.yaml` or directly in the comman line: `dbt run --models stg_payments --vars "{'databricks_skip_optimize': 'true'}"`
**Benefits:**
This simplifies the project as it requires one less post hook for maintenance operations.
* Add predicates to OPTIMIZE statement. `OPTIMIZE table WHERE ...`
* Do not fail model if optimize fails: warn if optimize fails, but not error our
=> [feat] Support ZORDER as a model config

dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/adapters.sql, dbt/include/databricks/macros/materializations/incremental/incremental.sql, dbt/include/databricks/macros/materializations/table.sql, tests/integration/zorder/models/multiple_zorder_model.sql, tests/integration/zorder/models/single_zorder_model.sql, tests/integration/zorder/test_zorder.py, tests/unit/test_macros.py
Resolves #122
This PR augments the dbt model config with:
```python
config(
materialized='incremental',
zorder="column_A" | ["column_A", "column_B"]
)
```
Under the hood, after every model with zorder is build (initial or incremental), we'll run a OPTIMIZE relation ZORDER BY () statement.
A var is available to skip OPTIMIZE if necessary: `databricks_skip_optimize`
One can set it in the dbt-project.yaml or directly in the comman line: `dbt run --models stg_payments --vars "{'databricks_skip_optimize': 'true'}"`
This simplifies the project as it requires one less post hook for maintenance operations.
* Add predicates to OPTIMIZE statement. OPTIMIZE table WHERE ... 
* Do not fail model if optimize fails: warn if optimize fails, but not error out
=> [feat] Support ZORDER as a model config (#292)

dbt/adapters/databricks/python_submissions.py
Related to #232 which will be solved in three steps:
1. (This PR) Add `python_submissions.py` to dbt-databricks
2. Update `DBCommand` class to automatically start the cluster using the command API if it is not already started.
2. Remove `DbtDatabricksJobClusterPythonJobHelper` since this execution method isn't supported on Databricks anymore
This pull request copies the contents of dbt-spark's `python_submissions.py` directly into dbt-databricks. This is the path proposed in https://github.com/dbt-labs/dbt-spark/discussions/407 now that Python models have been released in dbt 1.4. It is a precursor to fixing #232, which will require modifying the `DBCommand` class to start an all-purpose cluster as needed.
=> Copy python_submissions.py into dbt-databricks

dbt/adapters/databricks/python_submissions.py, tests/integration/python/models/basic.py, tests/integration/python/models/models.yml, tests/integration/python/test_python.py
Resolves #232
This change follows #302, which imported some Databricks-specific code from dbt-spark directly into this repository. In this PR I implemented logic to check whether the cluster for Python models is running, start it if not, and wait for the cluster to start before proceeding.
Testing this change is necessarily manual, for now. The test uses a `dbt` profile that connects to a SQL warehouse and then tells the specific Python model to connect to an all purpose cluster which is in TERMINATED state at the beginning of the test. Our automated integration tests run on shared infrastructure (multiple PRs use the same environment) so we can't guarantee that the all-purpose cluster is TERMINATED automatically.
Therefore the integration test in this PR is skipped automatically. To run …
=> Auto start cluster for Python models

requirements.txt, setup.py
Resolves #111 
Version 2.5.0 of databricks-sql-connector should allow dbt-databricks to run connect to Databricks through a proxy using the standard Python convention. The updated release also adds a saner retry policy when thrift commands fail because of a connection timeout.
=> Bump databricks-sql-connector to 2.5.0

tests/integration/base.py, tests/unit/utils.py
This is a mirror of dbt-spark#632
Resolves #
This PR applies the same fix from dbt-spark#632 to dbt-databricks so that `tox -e unit` now passes all tests.
=> Fix: parse vars in unit test utils for dbt==1.5.x

.gitignore, dbt/adapters/databricks/auth.py, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/python_submissions.py, dbt/include/databricks/profile_template.yml, dev-requirements.txt, docs/oauth.md, requirements.txt, setup.py, tests/profiles.py, tests/unit/test_adapter.py, tests/unit/test_auth.py
This PR adds support for OAuth: both 3-legged and 2-legged.
From a user perspective, `token` is not mandatory anymore. By default, OAuth with SSO (browser login) will be used.
For automation and CI/CD use cases, `client_id` and `client_secret` are now available as config.
It just works as long as admin has enabled `dbt-databricks` as an OAuth application:
```
curl -n -X POST https://accounts.cloud.databricks.com/api/2.0/accounts/<Account ID>/oauth2/published-app-integrations -d '{ "app_id" : "dbt-databricks" }'
```
Profile:
```yaml
type: databricks
host: "<your databricks host name>",
http_path: "<http path for warehouse >",
```
A Public client/ Native Azure AD Application must be created with redirect URL `http://localhost:8020`. For SSO, Azure Application (client) ID must be used for …
=> OAuth support

.gitignore, dbt/adapters/databricks/auth.py, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/python_submissions.py, dbt/include/databricks/profile_template.yml, dev-requirements.txt, docs/oauth.md, requirements.txt, setup.py, tests/profiles.py, tests/unit/test_adapter.py, tests/unit/test_auth.py
This PR adds support for OAuth: both 3-legged and 2-legged.
From a user perspective, `token` is not mandatory anymore. OAuth with SSO (browser login) will be used if `auth_type: oauth` is defined.
For automation and CI/CD use cases, `client_id` and `client_secret` are now available as config.
It just works as long as admin has enabled `dbt-databricks` as an OAuth application:
```
curl -n -X POST https://accounts.cloud.databricks.com/api/2.0/accounts/<Account ID>/oauth2/published-app-integrations -d '{ "app_id" : "dbt-databricks" }'
```
Profile:
```yaml
type: databricks
host: "<your databricks host name>"
http_path: "<http path for warehouse >"
auth_type: "oauth"
```
A Public client/ Native Azure AD Application must be created with redirect URL `http://localhost:8020`. For SSO, Azure …
=> [feat] OAuth support (#307)

CHANGELOG.md, dbt/include/databricks/macros/adapters.sql, docs/databricks-dbt-constraints-vs-model-contracts.md, tests/integration/persist_constraints/models/schema.yml, tests/integration/persist_constraints/models/table_model_contract.sql, tests/integration/persist_constraints/test_persist_constraints.py
=> [staging] Throw error if model contract enforced

CHANGELOG.md, dbt/adapters/databricks/impl.py
Resolves [#326](https://github.com/databricks/dbt-databricks/pull/326)
This PR allows the adapter to handle strings of more than 2048 characters when running show tables extended in Databricks. This is currently preventing users from being able to run this command when using dbt if they have a large number of tables in any given schema. 
The way this is done is that it will pass the `*` in instances where the string length of the pipe separated tables is more than 2048 chars.
I have successfully tested both unit tests and `tox -e integration-databricks-sql-endpoint`.
=> allow-table-extended-to-handle-more-than-2048-chars

tests/integration/model_contract/test_model_contract.py
Disable TestModelContractNotDelta until it can be redesigned
Signed-off-by: Raymond Cypher <raymond.cypher@databricks.com>
=> Disable integration test

dbt/adapters/databricks/connections.py, requirements.txt, setup.py
This resolves this issue I raised recently https://github.com/databricks/dbt-databricks/issues/348
Root cause is due to the renaming done in this PR: https://github.com/databricks/databricks-sdk-py/pull/116
These types of breaking changes are normal and part of life. Would like to see this get pushed through ASAP though.
* Bump to the `databricks-sdk` to use the latest version. 
* Rename the `RefreshableCredentials` references to `SessionCredentials`
It would be failing for anyone trying to connect to databricks using `dbt-core` and the `dbt-databricks` adapter if I'm not mistaken.
=> feat: bump databricks-sdk v0.1.7 and rename RefreshableCredentials to SessionCredentials

tests/integration/model_contract/test_model_contract.py
TestInvalidModelContractCheckConstraints tests that an invalid constraint causes a failure.  The test checked that the error message contained 'Constraint validation failed'. dbt 1.5.2 changed the error message to 'Contract enforcement failed'. Updated the test to check for either the original or updated message.
=> Fix failing model contract integration test

CHANGELOG.md, dbt/adapters/databricks/__version__.py, dbt/adapters/databricks/connections.py, dev-requirements.txt, requirements.txt, setup.py
This PR uses commits with good commit messages to explain each step of the process. It will be easiest to review commit-by-commit.
Resolves #381
The way I made this PR was to compare the tip of `1.5.latest` to the tip of `main` and only look at changed files that _haven't been touched by a PR since the last release (1.5.4)_.
This pull request uses several commits with relevant comments to explain what changes I made. The bulk of this is just updating the CHANGELOG on `main`.
There are three commits that actually affect code execution:
These three exact changes have been part of existing dbt-databricks releases and therefore should be safe to release now.
Everything else affects only the CHANGELOG or our development setup, which won't impact customers.
=> Synchronise changes from 1.5.latest back to main

tests/integration/materialized_view/test_materialized_view.py, tests/integration/streaming_table/test_streaming_table.py
temporarily disabling integration tests for streaming tables and materialized views
Signed-off-by: Raymond Cypher <raymond.cypher@databricks.com>
=> Disabled MV/ST integration tests

CHANGELOG.md, dbt/adapters/databricks/impl.py
Resolves [#326](https://github.com/databricks/dbt-databricks/pull/326)
This PR allows the adapter to handle strings of more than 2048 characters when running show tables extended in Databricks. This is currently preventing users from being able to run this command when using dbt if they have a large number of tables in any given schema. 
The way this is done is that it will pass the `*` in instances where the string length of the pipe separated tables is more than 2048 chars.
I have successfully tested both unit tests and `tox -e integration-databricks-sql-endpoint`.
=> allow-table-extended-to-handle-more-than-2048-chars (#326)

CHANGELOG.md, dbt/adapters/databricks/impl.py
This is a follow-on to #392 to completely implement the changes needed as a result of https://github.com/dbt-labs/dbt-core/pull/7545
Previously, I had only given guidance that `DatabricksConnectionManager.execute()` was the only place where limit should be added. 
However, TIL that dbt-databricks overrides dbt-core's [`BaseAdapter.execute()`](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/adapters/base/impl.py#L275-L290), therefore that function signature must also be updated. This was a miss on my part, because AFAIK, dbt-databricks is the only adapter doing this. I updated https://github.com/dbt-labs/dbt-core/discussions/7958 to reflect this information.
Perhaps there's a follow-up item where can revisit the use case of overriding that method and if there's an alternative way …
=> Another usage of limit param

CHANGELOG.md, dbt/include/databricks/macros/materializations/clone.sql, dev-requirements.txt, tests/functional/adapter/test_dbt_clone.py
Adds support for dbt clone.  I grabbed the materialization from dbt-spark to remove the filter for delta as the specified format, as Databricks can pass all of the fixture tests with shallow clone without setting file_format.
=> dbt clone support

dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/python.sql, setup.py, tests/unit/macros/test_python_macros.py
Fixes issues where incremental + external_location would complain about location overlap on incremental runs.  It does this by writing the temp tables to their own folder.  Note: since Databricks does not delete files in external locations when relations are dropped, owners will need to manage these folders themselves.
This support is experimental.
I have tested manually since we are still working on test infrastructure to run integration tests against external locations in github.  My manual tests involved two types of tests:
1.) verify that we can run the same dbt command 3 times.  Why 3?  To make sure that we can create the incremental staging tables repeatedly without complaint about overlapping location.
2.) verify that when using python models, incremental, and external locations, …
=> Patching external location support in python models

CHANGELOG.md, dbt/adapters/databricks/__version__.py, dbt/adapters/databricks/impl.py
Resolves #403
The change from #326 targets AWS Glue Catalog users but is enabled by default for all users. We need to reimplement that fix behind an environment variable so that admins can enable that behaviour only in the cases where they know they need it and can take responsibility for table access permissions.
Resolves
=> Fix: revert #326 which breaks DESCRIBE table for some non Glue Catalog users

CHANGELOG.md, dbt/adapters/databricks/impl.py, tests/unit/test_adapter.py
Resolves #325
Follow-on work after we reverted the original fix in #404.
The behaviour is now gated behind an environment variable called `DBT_DESCRIBE_TABLE_2048_CHAR_BYPASS`. When that environment variable is set to `true` then the fix is applied. Else we do not cap the joined table names length to 2048 characters. This 2048 limit only applies to Glue Catalog users and should not be applied to all dbt runs.
=> [PECO-921] (Reimplemented) Fix: allow DESCRIBE TABLE EXTENDED to handle more than 2048 characters

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/adapters.sql, dbt/include/databricks/macros/python.sql, tests/unit/macros/test_adapters_macros.py
Resolves https://github.com/databricks/dbt-databricks/issues/399
With this change, dbt user could supply `liquid_clustered_by` model config with column (or list of columns) to be used as clustering keys using **Liquid Clustering** feature of Delta. The change introduces a small change in DDL query, while it does nothing for `python`-based models (as I couldn't find the python API for **Liquid Clustering**).
=> Liquid Clustering config for table materialization

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/adapters.sql, tests/unit/macros/test_adapters_macros.py
Code has been reviewed and merged to a staging branch. This PR will run our e2e tests. 
See #398
=> Liquid Clustering config for table materialization (#398)

CHANGELOG.md, test.env.example, tests/functional/adapter/test_changing_relation_type.py, tests/functional/adapter/test_constraints.py, tests/functional/adapter/test_grants.py, tests/functional/adapter/test_python_model.py, tests/integration/base.py, tests/integration/conftest.py, tests/integration/copy_into/test_copy_into.py, tests/integration/debug/test_debug.py, tests/integration/fail_fast/test_fail_fast.py, tests/integration/get_columns_in_relation/test_get_columns_in_relation.py, tests/integration/incremental_on_schema_change/test_incremental_on_schema_change.py, tests/integration/incremental_strategies/test_incremental_strategies.py, tests/integration/materialized_view/test_materialized_view.py, tests/integration/model_contract/test_model_contract.py, tests/integration/persist_constraints/test_persist_constraints.py, tests/integration/persist_docs/test_persist_docs.py, tests/integration/python/test_python_autostart.py, tests/integration/run_results_json/test_run_results_json.py, tests/integration/seed_column_types/test_seed_column_types.py, tests/integration/set_tblproperties/test_set_tblproperties.py, tests/integration/store_failures/test_store_failures.py, tests/integration/streaming_table/test_streaming_table.py, tests/integration/zorder/test_zorder.py, tests/profiles.py, tox.ini
This pull request removes the databricks_sql_endpoint profile as redundant with databricks_sql_uc_endpoint.  Per this link, any warehouse connecting to a workspace with a metastore is a 'UC' endpoint, in contrast with clusters, which can be configured to be UC-(in)compatible: https://docs.databricks.com/en/data-governance/unity-catalog/compute.html.
This PR also changes all test methods that do not include a profile to be prefixed with an _ so that test runners do not assume they are independently runnable.
All tests have passed on our new testing infra.
Will update the changelog after review.
=> Removing databricks_sql_endpoint profile and ensuring all tests pass in VSCode

CHANGELOG.md, dbt/adapters/databricks/python_submissions.py, dbt/adapters/databricks/utils.py, tests/unit/test_utils.py
Resolves #355 
Removes ANSI color tags from strings in exceptions.  While these tags look great when you're monitoring a terminal, they are nearly incomprehensible when looking at the dbt.log.  As dbt-databricks does not control the code that emits to logs vs terminal, this change ensures that the python stack traces are always legible at the expense of not being as colorful as they would otherwise be.
=> Improve python stacktrace rendering in dbt.log

.github/workflows/integration.yml
Splits our integration test run UC cases out so that they can run in parallel.  Its possible that they will slightly interact when the SQL profile is running the python tests (since that also needs a cluster), so I will monitor for that, but the upshot is that when the SQL tests have a transient failure (which has been happening), we won't need to rerun, and wait for, the cluster tests.
=> Splitting uc test cases

CHANGELOG.md, dbt/adapters/databricks/auth.py
Including 'offline_access' as a scope in the m2m flow was breaking AWS OAuth.  After consulting with Jacky, it seems safe to remove for m2m flow, as it should only be needed for u2m flow.
=> Update m2m OAuth scopes to not include offline_access.

CHANGELOG.md, dbt/adapters/databricks/impl.py, tests/integration/avoid_describe_extended/models/new_model.sql, tests/integration/avoid_describe_extended/seeds/preexisting_data.csv, tests/integration/avoid_describe_extended/test_avoid_describe_extended.py
Resolves #442 
As of 1.6.0, we added logic to determine Streaming Tables from normal Tables using describe extended if the type isn't returned.  There's no reason to do this on hive, which also unfortunately does not return the type when you ask it to show tables.  This PR says that if an object was returned by show tables, and the database (catalog) is none or hive_metastore, return the type table without calling describe extended.
=> Avoid describe extended on hive_metastore

CHANGELOG.md, dbt/adapters/databricks/connections.py
Resolves #452 
Use the get_node_info method to populate node info into SQLQueryStatus. Tested locally and validated node_info is correctly populated in logs.
=> Add Node Info to SQLQueryStatus

CHANGELOG.md, requirements.txt, setup.py
Resolves #457 
Updating the Databricks SDK version to 0.9.0 so that we don't end up with dangerously outdated requests versions.
=> Updating the databricks-sdk dependency

CHANGELOG.md, dbt/adapters/databricks/python_submissions.py
This should fix the issue where multiple threads try to start the same cluster, and we get an exception saying the cluster is Pending.
=> Python: if the cluster is already starting up, just wait for it

CHANGELOG.md, dbt/include/databricks/macros/adapters.sql, tests/integration/base.py, tests/integration/liquid_clustering/models/liquid_clustered.sql, tests/integration/liquid_clustering/test_liquid_clustering.py, tests/integration/zorder/test_zorder.py, tests/unit/macros/test_adapters_macros.py
Resolves #448 
Discovered that we weren't running optimize with liquid_cluster_by because the optimize clause was only set up to respect z-ordering.
=> Ensure optimize is run with liquid_clustered_by

CHANGELOG.md, dbt/__init__.py
Resolves #470 
The addition of this file resolves the above linked issue. See below screenshot
=> fix vscode pylance import errors

CHANGELOG.md, dbt/adapters/databricks/python_submissions.py
Resolves #466 
I was unaware that users were doing some sophisticated things to do custom library installs from private locations.  This PR makes it so that we only explicitly specify the url if index_url is specified; this should allow defaulting to however pip is configured for the cluster.
=> Revert python library install behavior if index_url not specified

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/relation.py, dbt/include/databricks/macros/metadata.sql, tests/functional/adapter/test_source_freshness.py
Addresses the 'metadata freshness changes' part of https://github.com/dbt-labs/dbt-core/discussions/8307
Doing this in a way that can work for hive and unity was interesting.  I'm a little concerned about the accuracy/perf around the hive implementation, but its the best I can do, and I don't have a great way to insert a check for hive metastore earlier in the call chain.  
@dataders any concern that if someone has a view as a source (as is the case in my bigger transform jobs), then this mechanism doesn't work?  I didn't see if there was any logic that only called down to this path if the relation is a table.  Both using information schema in this way and describe history are table-only features.  I mean we could look at information_schema.views, but last altered doesn't give the same …
=> Implementing metadata freshness checks

CHANGELOG.md, dbt/adapters/databricks/connections.py
This is a follow-up to https://github.com/databricks/dbt-databricks/pull/453, which added `node_info` to the `SQLQueryStatus` event. This PR adds `node_info` to the `SQLQuery` event.
I did not open a separate issue for this as it feels very related to https://github.com/databricks/dbt-databricks/issues/452, but happy to log a new issue if desired!
Keeping this as draft for the moment while I get set up to run the linter and add a changelog entry.
=> Add node_info to SQLQuery events

.github/workflows/integration.yml, CHANGELOG.md, dbt/adapters/databricks/__version__.py, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/relation.py, dbt/include/databricks/macros/materializations/seeds/helpers.sql, dev-requirements.txt, requirements.txt, setup.py, tests/conftest.py, tests/functional/adapter/test_seeds.py
This PR includes
a.) change to get_catalog to account for changes that dbt made between 1.7.0rc1 and 1.7.0
b.) a fix for a PR I merged earlier that removed casts from seeding.  Turns out that with hive and parquet, the cast is necessary for numeric types; the tests passed initially because the old version of the copy_into tests didn't use seeds, and nowhere else in our project do we test parquet and seeds.
c.) a modification to our external location integration variable because something has changed (I think in the dbr) so that its extra sensitive to running in the top level of a container
=> 1.7.0 Compat

dbt/adapters/databricks/connections.py, dbt/adapters/databricks/impl.py, tests/functional/adapter/warehouse_per_model/fixtures.py, tests/functional/adapter/warehouse_per_model/test_warehouse_per_model.py, tests/unit/test_compute_config.py
Resolves PECO-1182
Allows models in a dbt project to run on different SQL warehouses.
The available warehouses are specified as named values in the dbt profile.
The configuration for a model can specify by name which warehouse it should run on.
=> Allow models to execute on different warehouses

dbt/adapters/databricks/impl.py, dbt/adapters/databricks/relation.py, dbt/include/databricks/macros/catalog.sql
Resolves #496, I hope
So we think when no models are selected, stuffing the where clause with every model is probably non-performant.  In dbt core, they'll only call get_catalog if no models are selected, or there are more than 100 models selected.  In this case, we can filter by schemas, but probably a bad idea to make our optimizer try to handle a where clause with 200+ components.
=> Another attempt to improve metadata gathering performance

tests/functional/adapter/basic/test_adapter_methods.py, tests/functional/adapter/basic/test_base.py, tests/functional/adapter/basic/test_docs_generate.py, tests/functional/adapter/basic/test_empty.py, tests/functional/adapter/basic/test_ephemeral.py, tests/functional/adapter/basic/test_generic_tests.py, tests/functional/adapter/basic/test_incremental.py, tests/functional/adapter/basic/test_singular_tests.py, tests/functional/adapter/basic/test_singular_tests_ephemeral.py, tests/functional/adapter/basic/test_snapshot_check_cols.py, tests/functional/adapter/basic/test_snapshot_timestamp.py, tests/functional/adapter/basic/test_table_materialization.py, tests/functional/adapter/basic/test_validate_connection.py, tests/functional/adapter/caching/test_caching.py
Per discussion on previous PR, dropping Databricks prefixes from tests, as they live in our namespace and so are clearly Databricks adapter tests.
Adds 3 more missing functional test categories.
=> More test refactoring, adding missing tests

dbt/adapters/databricks/connections.py
When looking at debug logs, allows us to see if/when we use different computes.  It's a little rough because you have to map thread id to find out if its used where you expect it, but we can clean up before final release.
=> Adding logging for warehouse per model

dbt/adapters/databricks/connections.py, tests/functional/adapter/warehouse_per_model/fixtures.py, tests/functional/adapter/warehouse_per_model/test_warehouse_per_model.py, tests/unit/test_compute_config.py
- Updated the debug logging for warehouse-per-model to include thread id and relation name. 
- Updated the warehouse-per-model functional tests to include a seed and a snapshot that specify an alternate compute.  Changed the test conditions to include checking log output for messages that indicate the alternate compute was used.
=> Updates to warehouse-per-model logging and tests

.gitignore, CHANGELOG.md, dbt/adapters/databricks/python_submissions.py, tests/integration/python/models/complex_config.py, tests/unit/python/test_python_submissions.py
Pulled in https://github.com/databricks/dbt-databricks/pull/516 to run on our infra, as well as expanding to work with All Purpose clusters when submitted as a notebook job.  Unit tests only for now, as it's very complicated to validate the permissions in the test environment.
=> Enable access control for job runs

dbt/adapters/databricks/connections.py, tests/functional/adapter/long_sessions/fixtures.py, tests/functional/adapter/long_sessions/test_long_sessions.py, tests/unit/test_idle_config.py
=> Long sessions

dbt/adapters/databricks/connections.py, tests/functional/adapter/long_sessions/test_long_sessions.py, tests/functional/adapter/warehouse_per_model/test_warehouse_per_model.py
Fixes minor test log bugs for WPM and long sessions.
=> Fix minor test bug for WPM

dbt/adapters/databricks/connections.py
Resolves #464
The inclusion of the backticks was causing list_schemas to return only 'global_temp'.  This meant that the precaution in dbt-core to not try to create schemas that already exist wasn't seeing the correct list of schemas.
=> Fixing list_schemas so that we stop trying to create schemas that exist

tests/integration/base.py
Resolves #
Currently we can not test schema uppercase. There are some issue when we pass the schema uppercase. Talking in this PR.
https://github.com/databricks/dbt-databricks/pull/530#issuecomment-1851214791
This change will pass the schema without converting to lowercase and will  help to test schema uppercase. 
Execute integration test and confirm from query history that this change apply as I expected. Schema is passed by upper case `test17038406285517460420_Incremental_strategies `
```
insert
overwrite `catalog_demo`.`test17038406285517460420_Incremental_strategies`.`expected_append`
values
(1.0, 'hello'),(2.0, 'goodbye'),(2.0, 'yo'),(3.0, 'anyway')
```
=> Eliminate the conversion of the schema to lowercase for schema-related test

.github/workflows/build_cluster_http_path.py
By switching the method we use to find the workspace id, we are now immune to the fact that workspace ids may be of different lengths.  If we ever switch to testing on AWS, we'll need to revisit this.  Also added some fluff to make mypy happy, since I've turned on mypy checking in my IDE.
- [] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-databricks next" section.
=> Fix the integration runner to correctly find workspace_id

CHANGELOG.md, dbt/adapters/databricks/connections.py
When python models run for 15+ minutes, the user may get an error related to a previously open session having been closed.  This PR fixes that issue by ensuring we recreate connections that are older than 10 minutes before use.
=> Fixing Python-related timeouts

tests/conftest.py, tests/functional/adapter/long_sessions/test_long_sessions.py, tests/functional/adapter/warehouse_per_model/test_warehouse_per_model.py
There is a bug in the dbt testing infrastructure: 
"[CT-3478] [Bug] Editing profiles as part of tests is not thread-safe #9254" 
https://github.com/dbt-labs/dbt-core/issues/9254 
This causes issues for tests that use the profiles_config_update fixture. 
Added class level fixture dbt_profile_data to conftest.py.  
This creates the profile used by all the tests, in it additional targets are added to be used by the tests that were formerly using profiles_config_update. 
Updated the tests to remove the profiles_config_update fixture and to specify the appropriate target when running.
=> Updated tests that were modifying the dbt profile

CHANGELOG.md, dbt/adapters/databricks/connections.py
Resolves:
[ES-985588: dbt-databricks data models timeout](https://databricks.atlassian.net/browse/ES-985588)
A long running python model can leave a connection/session idle for long enough that it times out and is closed.
Subsequent use of the connection results in an 'Invalid Sessionhandle' error.
For non-python data models the model is executed using sql statements.  So even if the sql statement takes a long time to run, the connection is in active use and doesn't timeout on the server.  For a python model a connection is acquired, but the model is run using rpc calls. Thus, if the python model takes a long time to run, the session can timeout on the back end.
The code to cleanup idle connections was not catching this because when a connection is released, after running a model, the …
=> Python model specific session handling to prevent using invalid sessions

CHANGELOG.md, dbt/adapters/databricks/python_submissions.py, tests/unit/python/test_python_submissions.py
Make the python model code more resilient to random API failures by specifying a retry with backoff policy.
=> Adding a default retry strategy in python submissions

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/relations/drop.sql
Streaming tables were always being dropped and recreated instead of being refreshed. This was due to streaming tables being incorrectly identified as regular tables. 
The _parse_type() function was returning a type string of "Type:STREAMING_TABLE".  The calling code was expecting just the string "STREAMING_TABLE" and so wasn't correctly identifying streaming tables.
Updated the _parse_type() function to return the expected type string, ie stripped away the "Type:" part. 
After fixing the table type parsing testing showed that this exposed an issue with dropping streaming tables.
Implemented macro databricks__drop_relation so that we use the correct sql to drop a streaming table 
Signed-off-by: Raymond Cypher <raymond.cypher@databricks.com>
=> Fixed issue with streaming tables always being dropped

CHANGELOG.md, dbt/adapters/databricks/connections.py, requirements.txt, setup.py
Upgrades to databricks-sql-connector 3.0.0 so as to get pyarrow upgraded; requires passing use_inline_params=true in order to accommodate how seeds work.
=> Upgrade to databricks-sql-connector

CHANGELOG.md, dbt/adapters/databricks/impl.py, tests/conftest.py
Improves #556 
If the relation we are enumerating for is Hive, we don't need show tables extended in order to determine the types of the materializations (we only have the options of view or table).  This PR removes this extra show table step, and returns to the old behavior for Hive.
=> Improve hive list relations behavior

dbt/adapters/databricks/connections.py
This is a follow-up to #555 to fix a typo in `connections.py`. I have confirmed that this PR now passes the `TestMaterializedView` tests. The value of `self._cursor.connection.thrift_backend._auth_provider._header_factory` is a callable which is instantiated by `BearerAuth` and returns a dictionary. So we don't need to call it from `connections.py`.
No addition to the changelog since the previous PR hasn't been released yet.
=> [PECO-1387] mv/st: Fix typo in #555

CHANGELOG.md, requirements.txt, setup.py
We started getting a variety of tests failing with pandas 2.2.0; for now, pinning the version to 2.1.x, and monitoring the situation on pandas.
=> Pinning pandas to stop test errors

CHANGELOG.md, dbt/adapters/databricks/connections.py
Normalized logging of connection debugging messages to be consistent and contain more information in a more easily usable format. When the databricks session is actually opened the last used time of the connection object is now being set.
=> Connection debugging logging and set last used time on open session

CHANGELOG.md, dbt/adapters/databricks/connections.py
This PR adds some additional logging for connection errors. While debugging dbt issues over the past few weeks, I ran into errors like "Access denied to clusters that don't have Unity Catalog enabled." Without this patch, they are not shown to the user.
=> Show details with connection errors

CHANGELOG.md, dbt/adapters/databricks/connections.py
Migration of #588 to fix linting and minor changelog.
Resolves #587 
The type annotation `ResultNode` from dbt-core should guarantee that an object has a `relation_name` property. In practice, the object passed by dbt-core to the functions modified by this PR do not always have that property. In particular, the `node` object might be a `SavedQuery`, which does not have `relation_name`.
This PR adds explicit checks to work around the issue when `relation_name` is missing.
=> Migrate #588: Work around a type annotation mistake

CHANGELOG.md, dbt/include/databricks/macros/materializations/incremental/strategies.sql
Using the previous form, if there was a null value in a unique key when trying to merge an incremental run, it would lead to a duplicate row (since NULL = NULL evaluates to false).
=> Use null safe comparison for merge sql

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/relation.py
Resolves #598 
After discussing with @mikealfare I believe this should have minimal issues, given that the tables in question are temporary and should not be interacted with by a separate thread than the one that produced them.  If having an unknown type is actually problematic, this merely moves where the error will be realized, so should be no worse than current behavior, while at the same time improving behavior when the table is irrelevant.
=> Do not fail when we cannot determine the table type

CHANGELOG.md, dbt/include/databricks/macros/materializations/incremental/strategies.sql, tests/functional/adapter/incremental/test_incremental_on_schema_change.py, tests/unit/macros/relations/test_incremental_macros.py
A github user pointed out that technically using NULL could lead to different behavior than *, where DEFAULT would be honored for missing columns, so I have adjusted `insert into` to use DEFAULT instead.  Also, noticed that at some point I lost my config that made the append tests actually test append, so added that back.  The second half of the 'append columns' test for the append strategy validates that DEFAULT is used and does not break.
=> Prefer DEFAULT to NULL when inserting into, actually validate append

CHANGELOG.md, dbt/adapters/databricks/connections.py
Resolves issue where serverless requests were dying just before the query completed due to socket timeout set at 3 minutes.  I think this has to do with either compute availability or direct result choice by Thrift server, but either way, we have seen instances where the query is killed at 3 minutes, but since closing the session doesn't actually cancel the work, the query completes successfully at around 4 minutes.
=> Up default socket timeout to 600

dbt/adapters/databricks/connections.py, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/logging.py, dbt/adapters/databricks/python_submissions.py
Refactors logger construction out into a single location to reduce code replication and isolate logging logic from otherwise complicated files.
=> Refactor logger out

dbt/adapters/databricks/connections.py, dbt/adapters/databricks/impl.py
Still WIP, but trying to address some things that have broken or could be refactored for clarity.  Starting with USE_LONG_SESSIONS=false should work (it stopped with the addition or more logging).
=> Connection management clean up

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/relation_configs/incremental.py, dbt/adapters/databricks/relation_configs/tags.py, dbt/include/databricks/macros/materializations/incremental/incremental.sql, dbt/include/databricks/macros/materializations/table.sql, dbt/include/databricks/macros/materializations/view.sql, dbt/include/databricks/macros/relations/tags.sql, tests/conftest.py, tests/functional/adapter/incremental/fixtures.py, tests/functional/adapter/incremental/test_incremental_tags.py, tests/functional/adapter/tags/fixtures.py, tests/functional/adapter/tags/test_databricks_tags.py, tests/unit/macros/relations/test_tags_macros.py, tests/unit/relation_configs/test_incremental_config.py, tests/unit/relation_configs/test_materialized_view_config.py, tests/unit/relation_configs/test_tags.py, tests/unit/relation_configs/test_tblproperties.py
Resolves #606
Adds support for setting tags (for discovery, governance) on tables/views.  Unfortunately not yet supported on MV/STs, but I built the support in the same way I do on_config_change for them, so it should be trivial to add when they become supported.
=> Supporting tags

CHANGELOG.md, dbt/include/databricks/macros/materializations/incremental/incremental.sql, dbt/include/databricks/macros/materializations/table.sql, dbt/include/databricks/macros/relations/tblproperties.sql, tests/functional/adapter/python_model/fixtures.py, tests/functional/adapter/python_model/test_python_model.py
It was an oversight that python models did not support specifying tblproperties in any way.  This remedies that, but with a major caveat: because DataframeWriterV1 doesn't support tableProperty (and DataframeWriterV2 does not currently work in the execution env), we can't set tblproperties at table creation.  Or more aptly, we might be able to, but it would be a significant rewrite, where we create a table (including specifying column types, ugh) and the insert the data into it as separate steps, so that we could get tblproperties set using the SQL API.
What does that mean?  It means that if you want to use tblproperties to anotate your python-generated tables with metadata, you'll now be able to.  If, however, you were hoping to use tblproperties on python models to enable some advanced …
=> Support tblproperties (weakly) in python models

CHANGELOG.md, dbt/adapters/databricks/__version__.py, dbt/adapters/databricks/connections.py
Was about to release 1.7.12 when I noticed this chunk of code.  Need to understand why this never used the user-provided client_id.
=> Missed oauth change?

dbt/adapters/databricks/connections.py, docs/oauth.md
Resolves #582 
As @benc-db  mentioned [here](https://github.com/databricks/dbt-databricks/issues/582#issuecomment-2040622059), it could be worth adding user configurable options for oauth apps to profiles.
@benc-db adds `oauth_redirect_url` to profiles.yml in #638  but we also need to make `oauth_scopes` user-configurable.
Given the app connection:
Profile configuration would be:
```yaml
jaffle_shop:
outputs:
test:
catalog: CATALOG
host: WORKSPACE_URL
http_path: /sql/1.0/warehouses/WAREHOUSE_ID
schema: SCHEMA
threads: 10
auth_type: oauth
oauth_redirect_url: "http://localhost:8050"
oauth_scopes:
- sql
- offline_access
type: databricks
target: test
```
=> FIX #582: User Configurable OAuth Scopes in profiles.yml

CHANGELOG.md, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/events/base.py, dbt/adapters/databricks/events/connection_events.py, dbt/adapters/databricks/events/credential_events.py, dbt/adapters/databricks/events/cursor_events.py, dbt/adapters/databricks/events/other_events.py, dbt/adapters/databricks/events/pipeline_events.py, tests/functional/adapter/long_sessions/test_long_sessions.py, tests/functional/adapter/warehouse_per_model/test_warehouse_per_model.py, tests/unit/events/test_base_events.py, tests/unit/events/test_connection_events.py, tests/unit/events/test_cursor_events.py
Hopefully resolves #647
Customers with high concurrency on SQL Warehouses have been hitting an issue where they see 'Remote disconnected' as the error.  It appears somewhere in the stack, connections that have been idle for 180+s hit this issue when we attempt to reuse them.  This PR has the following:
* Move default time for considering a connection stale to 60s (most of the benefit of reusing connections comes from having many quick operations anyway, since the overhead of creating and closing connections is sub-second).
* Significant refactoring of logging to improve clarity and consistency in debug logs
* I noticed that BearerAuth was invoking the header factory on create rather than call, which I believe is what was causing #647
I should probably add tests for the logging, but I will …
=> Fixing idle issue and improving debug logging

dbt/adapters/databricks/relation.py, dbt/include/databricks/macros/adapters/catalog.sql, dbt/include/databricks/macros/adapters/metadata.sql
Resolves #601
MANAGED_SHALLOW_CLONE is a new type that we were not handling.  The aim with this PR is a.) to stop 'interpreting' the table type when making the catalog, and b.) treat clones as tables for performing dbt operations.
=> Treat MANAGED_SHALLOW_CLONE as a table

.github/workflows/integration.yml, tests/unit/test_adapter.py
Remove dependence of the adapter tests on unittest (and instead depend on pytest).  Also updates some lagging references to the shared adapter libraries, that were still pointing at dbt-core.
=> Remove dependence on unittest from Adapter tests

CHANGELOG.md, dbt/adapters/databricks/events/connection_events.py
Users have reported that the logged message on connection opening errors is confusing.  This is due to passing None for the connection and then getting an error about the connection not being defined.
=> Backport fix to log events

CHANGELOG.md, dbt/include/databricks/macros/materializations/seeds/helpers.sql, dbt/include/databricks/macros/materializations/seeds/seeds.sql, tests/conftest.py, tests/functional/adapter/persist_docs/fixtures.py, tests/functional/adapter/persist_docs/test_persist_docs.py
Resolves #296 
This PR fixes an issue that users hit when repeatedly using `dbt build` with `persist_docs` and `seeds`.  Spark treats the lack of comments (since historically comments were applied with an ALTER statement) as a schema change, and since dropping an external location doesn't get rid of the backing data, Spark acts as though the table still exists with the previous schema after dropping.  I noticed while running my tests to verify the behavior that our create table command was specifying the column types, even when my model config did not; this is because dbt infers the types for seeds from the data in the seed file.  Having column type info in our create request means that we can also specify our comments during create for seeds, something we cannot do with normal table …
=> Fix for rerunning seed with persist_doc

CHANGELOG.md, dbt/adapters/databricks/relation_configs/comment.py, tests/functional/adapter/materialized_view_tests/fixtures.py, tests/functional/adapter/streaming_tables/test_st_changes.py, tests/unit/relation_configs/test_comment.py
Prior to this change, when a user had not put a description on his model, we actually set the table comment as ''.  This change ensures empty strings are not treated as legitimate comments.
=> Handle empty comments on MV/ST better

CHANGELOG.md, dbt/adapters/databricks/__version__.py, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/events/connection_events.py
I didn't realize that even if an input is optional, Python complains if you use a variable that hasn't been initialized, which gets in the way of users seeing the exception about why the connection couldn't be established.
=> Fix issue with conn not initialized

CHANGELOG.md, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/events/pipeline_events.py, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/relation_configs/refresh.py, dbt/adapters/databricks/relation_configs/tblproperties.py
If a scheduled refresh is already in progress when you request a refresh, you get an exception.  Exception handling during a materialization is gnarly, so instead, I ensure that any in progress pipelines are completed before we do any further processing of an MV/ST.
This PR also removes polling for completion of a create or refresh kicked off by dbt, as those operations are now synchronous by default.  Since I already have the pipeline id when I do need to check the refresh state, I can get rid of the API call we were using to get the pipeline id, which fixes another bug: refresh for MV/ST wasn't working in dbt-databricks if you needed to escape your relation name (since we had to strip off the escaping to call the API).
=> Handle in-progress refresh for MV/ST

CHANGELOG.md, dbt/include/databricks/macros/materializations/incremental/incremental.sql, tests/conftest.py, tests/functional/adapter/incremental/fixtures.py, tests/functional/adapter/incremental/test_incremental_strategies.py
Resolves #687
We had removed the spark setting for insert overwrite so that the strategy could be compatible with SQL Warehouses, but upon further reflection, it's unclear if the strategy is even useful for incremental tables without the setting, as it will just replace the entire table.  The consequence of having removed the spark setting was regressing users that were successfully using the strategy with clusters.
=> Reverting the decision to remove dynamic setting

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/adapters/catalog.sql, dbt/include/databricks/macros/adapters/metadata.sql, dbt/include/databricks/macros/relations/tags.sql, tests/conftest.py, tests/functional/adapter/incremental/test_incremental_tags.py, tests/functional/adapter/materialized_view_tests/fixtures.py, tests/functional/adapter/streaming_tables/fixtures.py, tests/functional/adapter/tags/test_databricks_tags.py, tests/unit/macros/relations/test_tags_macros.py
Resolves #691 
Today, information_schema does not work as expected when the name of a catalog is changed, as the catalog-specific views are written at create time and not updated.  While I'm pursuing that fix internally, switching over to system for all information_schema queries will fix this.  Unclear yet whether this will have any performance or governance implications (testing currently), though since all of the catalog-specific views reference system under the hood, I wouldn't expect any.
=> Attempt changing over to system for metadata gathering

CHANGELOG.md, dbt/include/databricks/macros/materializations/incremental/incremental.sql, tests/conftest.py, tests/functional/adapter/incremental/fixtures.py, tests/functional/adapter/incremental/test_incremental_replace_table.py
Resolves #696
The setting that enables insert_overwrite to selectively overwrite partitions also causes it to leave behind partitions when used with `create or replace`.  Hence, ensure the setting is static on 'full-refresh', and dynamic on subsequent runs.
=> Fix insert_overwrite replacement edge case

CHANGELOG.md, dbt/adapters/databricks/credentials.py
The default redirect_url `http://localhost:8020` and scope `all-apis` is not configured in the OAuth client `dbt-databricks`, which leads to the failure in OAuth U2M flow with the default OAuth configuration in the dbt profile.
Change the default `redirect_url` and scopes of OAuth client `dbt-databricks` to align its configuration in Databricks
- redirect_url: http://localhost:8050
- scope: `[sql, offline_access]`
=> Change default redirect_url and scopes of client dbt-databricks

CHANGELOG.md, dbt/include/databricks/macros/adapters/metadata.sql
Resolves #712 
Core issue is that I missed one of the places that I needed to add a clause to specify the catalog when I switched over to using system information_schema
=> Fix #712: missing catalog in one place

CHANGELOG.md, dbt/include/databricks/macros/materializations/seeds/helpers.sql
fix: address dbt seed command  error when seed file is partially defined in the config file
Resolves #723
=> Fix dbt seed command error when seed file is partially defined in the config file

CHANGELOG.md, dbt/adapters/databricks/relation.py, tests/conftest.py
Resolves #721 
Readds the external type.  This is slightly confusing because EXTERNAL as a type in Databricks just means that table is stored in the customers storage location, but from the attached bug, it sounds like not having it as a materialization type can cause some adapter compliance issues.
=> Readd external type

CHANGELOG.md, requirements.txt, setup.py
Upgrades our dependency to databricks-sql-connector to >=3.2.0,<3.3.0.  Ignore the branch name; I forgot that we need to remove the pin in PySQL before we can remove the pin here.
=> Upgrade to PySQL 3.2.0

CHANGELOG.md, dbt/include/databricks/macros/relations/constraints.sql
Resolves #676 
This PR makes sure that the column constraints are added before the table constraints.
The order matters for the primary_key constraint, which requires the column to have a not_null constraint. At a later moment, I suppose, the unique constraint should be present too.
I don't think the order matters for other (supported) contraints.
I am not sure how to build and test this yet. Existing unit tests seem to still work.
=> #676 pk constraint

CHANGELOG.md, dbt/include/databricks/macros/adapters/catalog.sql, dbt/include/databricks/macros/adapters/databricks_catalog.sql, dbt/include/databricks/macros/adapters/metadata.sql, dbt/include/databricks/macros/adapters/persist_docs.sql, dbt/include/databricks/macros/relations/tags.sql, tests/functional/adapter/basic/test_incremental.py
Incremental tables were potentially not running incrementally if components were specified with capitalization, as in information_schema they are always present in lowercase.  Talking to dbt to see if there is a better way to do this, but for now, ensure lower case when used in queries.
=> Fix capitalization issue

CHANGELOG.md, dbt/adapters/databricks/__version__.py, dbt/adapters/databricks/column.py, dbt/adapters/databricks/impl.py
Backports close cursor code to 1.7
=> Backport close cursor code to 1.7

CHANGELOG.md, dbt/adapters/databricks/python_submissions.py
Resolves #347
When multiple threads attempt to start a cluster, it's possible that the check [here](https://github.com/databricks/dbt-databricks/blob/37e16a5b5238f0d8cb7b99777db9fb6e8efeb7f3/dbt/adapters/databricks/python_submissions.py#L334) is True, but by the time it tries to trigger cluster start [here](https://github.com/databricks/dbt-databricks/blob/37e16a5b5238f0d8cb7b99777db9fb6e8efeb7f3/dbt/adapters/databricks/python_submissions.py#L392), the cluster has already been started by another thread and is in "RUNNING" or "PENDING" status. 
In such cases API returns an error "Cluster [cluster_id] is in unexpected state Pending." or "Cluster [cluster_id] is in unexpected state Running."
Current logic throws exceptions in this case. This fix allows it to continue and wait for cluster …
=> fix: race condition on cluster creation

.pre-commit-config.yaml, CHANGELOG.md, dbt/include/databricks/macros/adapters/persist_docs.sql, dbt/include/databricks/macros/materializations/incremental/incremental.sql, dbt/include/databricks/macros/materializations/materialized_view.sql, dbt/include/databricks/macros/materializations/snapshot.sql, dbt/include/databricks/macros/materializations/streaming_table.sql, dbt/include/databricks/macros/materializations/table.sql, tests/functional/adapter/dbt_clone/fixtures.py, tests/functional/adapter/dbt_clone/test_dbt_clone.py, tests/functional/adapter/incremental/fixtures.py, tests/functional/adapter/incremental/test_incremental_persist_docs.py, tests/functional/adapter/python_model/test_python_model.py, tests/functional/adapter/simple_snapshot/fixtures.py, tests/functional/adapter/simple_snapshot/test_snapshot.py
Resolves #732
- Update table comments for incremental models on incremental runs
- Update table comments for snapshots on incremental runs
- Create table comments during dbt clone
- Check for `config.persist_relation_docs()` in `persist_docs`
- Align black versions in `black.ini` and `.pre-commit-config.yaml` to fix failing `pre-commit` runs
The issue is only about the incremental models. While working on the PR I realized table comments are also not being updated for snapshots and are not created with `dbt clone`.
I think comments are also not being updated in materialized views and streaming tables. Since I don't have a good understanding of those materializations, I kept the original behavior by setting `for_relation=False`. The tests would also run through with `for_relation=True`, …
=> Fix table comment updates

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/relation_configs/base.py, dbt/adapters/databricks/relation_configs/incremental.py, dbt/adapters/databricks/relation_configs/tags.py, dbt/include/databricks/macros/materializations/incremental/incremental.sql, dbt/include/databricks/macros/materializations/table.sql, dbt/include/databricks/macros/relations/tblproperties.sql, tests/functional/adapter/incremental/fixtures.py, tests/functional/adapter/incremental/test_incremental_tblproperties.py, tests/unit/relation_configs/test_incremental_config.py
Addresses #760 (doesn't fully resolve because 760 also discusses comment updates)
Incremental tables have not been updating tblproperties on incremental runs.  This PR adds support for add/replace tblproperties on incremental run.  Delete was tested, but too risky/complicated, as Databricks sets some tblproperties for tables on its own.
=> Update tblproperties on incremental runs

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/materializations/incremental/strategies.sql, docs/databricks-merge.md, tests/functional/adapter/incremental/fixtures.py, tests/functional/adapter/incremental/test_incremental_predicates.py, tests/functional/adapter/incremental/test_incremental_strategies.py, tests/unit/macros/relations/test_incremental_macros.py
Resolves #245 
Resolves #707 
The current MERGE INTO capabilities available in dbt (data build tool) significantly differ from what can be achieved through a pure SQL interface. While it is sometimes possible to circumvent these limitations using complex SQL techniques, this approach often increases code complexity. Additionally, because Spark does not execute some operations identically when comparing direct merges with workaround solutions, this can lead to performance issues.
This PR aims to add the following capabilities:
- Add flag `skip_matched_step` to be able to skip matched step in merge statement. This and other mentioned flags are considered active only if they equal to a `true` string (case-insensitive).
- Add flag `skip_not_matched_step` to be able to skip not matched step in …
=> Extend Merge Capabilities

CHANGELOG.md, dbt/adapters/databricks/credentials.py
Resolves #
We have change the default scope for the dbt-databricks app to all-apis, offline_access, we also change the redirect url to https://localhost:8020, https://localhost:8050 in all AWS and GCP and Azure public regions. For Azure GovCloud regions it is still pending.
For Azure in the current python sdk(0.17.0) we will always redirect to [Azure endpoint](https://github.com/databricks/databricks-sdk-py/blob/v0.17.0/databricks/sdk/core.py#L841) so it does not affect how OAuth U2M works on Azure workspace at all.
This PR remove the hardcoded override for scopes and redirectUrls.
=> change oauth default scope

CHANGELOG.md, dbt/include/databricks/macros/relations/constraints.sql, tests/unit/macros/relations/test_constraint_macros.py
Resolves #747 
- Add the relation identifier (i.e. table name) to the auto generated name of constraints
- For foreign-key constraints, add either the statement of the list of columns including the parent column
=> Issue 747 primary key autoname

.github/workflows/integration.yml, .github/workflows/main.yml
Unit tests had started failing due to outdated Github Action.  This pr updates the use of that action and turns off running integration tests for changes to the unit test and stale jobs.
=> Update to upload-artifacts v4

CHANGELOG.md, dbt/include/databricks/macros/relations/constraints.sql, tests/unit/macros/relations/test_constraint_macros.py
Added an option to create custom constraints. A usecase could be creating TIMESERIES primary keys.
=> Add custom constraint option

CHANGELOG.md, dbt/include/databricks/macros/relations/constraints.sql, tests/functional/adapter/constraints/fixtures.py, tests/functional/adapter/constraints/test_constraints.py, tests/unit/macros/relations/test_constraint_macros.py
Resolves #784 
Looking into #784, constraints strip off config that dbt hasn't specified, so parent and parent_columns were not making it to the macro.  It looks as though 'to' and 'to_columns' can fill this role instead.  Will need to update any documentation out there that references parent and parent_columns.
=> Fix foreign key constraints

CHANGELOG.md, dbt/include/databricks/macros/adapters/metadata.sql
Add new type handling for external shallow clones.  Much like managed shallow clones, we need to collapse the type to something that dbt knows how to handle.
=> Handle external shallow clone

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/adapters/persist_docs.sql, dev-requirements.txt, requirements.txt, tests/functional/adapter/columns/fixtures.py, tests/functional/adapter/columns/test_get_columns.py
Resolves #779 (for UC)
`DESCRIBE EXTENDED` truncates column types.  For generating doc site, this is ok, but for running a dbt project, it can cause issues.  Where information_schema is available, we can use it to get an un-truncated column type.  Initially I was going to hide this behind a behavior flag, since both methods can have performance issues; however, during implementation I discovered that behavior flags aren't available to adapters yet, due to the current dbt-core not having flags on the RuntimeConfig object.  So, plan is to use information_schema where available, as it is more correct.  Once behavior flags are available, we can allow users to choose, so that if one way is less performant, they can switch.
=> Fix for describe column types

CHANGELOG.md, dbt/include/databricks/macros/relations/liquid_clustering.sql
Resolves #805
This fixes 805, though 805 raises a bigger question about whether its reasonable for users to materialize things outside of dbt, and expect dbt to handle that gracefully if you don't add matching config to the project.  Setting that aside, actually getting rid of this clause because I think it's more reasonable for someone to do a full refresh if they want to get rid of liquid clustering than it is to run cluster by none on every Delta incremental run.
=> Stop setting cluster by to None

CHANGELOG.md, dbt/adapters/databricks/behaviors/columns.py, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/utils.py, dbt/include/databricks/macros/adapters/persist_docs.sql, dev-requirements.txt, requirements.txt, setup.py, tests/conftest.py, tests/functional/adapter/columns/fixtures.py, tests/functional/adapter/columns/test_get_columns.py, tests/functional/adapter/python_model/fixtures.py, tests/functional/adapter/python_model/test_python_model.py, tests/unit/test_adapter.py
Partial fix for #779
This is my second attempt at addressing the issue that describe extended can truncate complex types.  With the release of dbt-core 1.8.7, we can now process behavior flags; this PR introduces the choice of using information_schema for grabbing column information in get_columns_for_relation.  I'm hiding behind a behavior flag because given the current state of UC information_schema, we have to run repair to trust that columns of recently created or altered table will be present in the information_schema, which adds overhead.  Furthermore, this trick only works for Delta tables at this time.  It is hoped that in time the sync issue with information_schema will be solved, but in the mean time, users can use this flag when they have complex types that describe extended …
=> Behavior: Get column info from information_schema Part I

CHANGELOG.md, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/relation_configs/table_format.py, dbt/adapters/databricks/relation_configs/tblproperties.py, dbt/include/databricks/macros/relations/components/tblproperties.sql, dbt/include/databricks/macros/relations/tblproperties.sql, dev-requirements.txt, requirements.txt, setup.py, tests/conftest.py, tests/functional/adapter/constraints/fixtures.py, tests/functional/adapter/iceberg/fixtures.py, tests/functional/adapter/iceberg/test_iceberg_support.py, tests/unit/macros/relations/test_table_macros.py
Adds table_format: iceberg, to match support of other dbt-adapters.  This config sets a table or incremental materialization as iceberg compatible via UniForm.  Note: once a table is made iceberg compatible, removing the table_format will not remove the tblproperties, as we currently find doing tblproperty deletes on behalf of the user to be too fragile for most use-cases.
=> Simple Iceberg support

dbt/adapters/databricks/connections.py, dev-requirements.txt, tests/functional/adapter/constraints/fixtures.py
This is the minimal PR required to get 1.8.x tests to stop failing due to dbt-core 1.9.0-b1 and friends.
=> Fixing failing tests from newer dbt versions

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/materializations/incremental/incremental.sql
Resolves #
Set unique table suffix to allow parallel incremental execution
For some specific cases (eg. backfill very large amount of data), we need to execute parallel multiple dbt run of specific incremental(replace_where) model in which we pass the date (or country) as var argument.
For example, we have a model we run every day using Airflow for which we pass the a date relative to the Airflow scheduler.
FYI
https://github.com/dbt-labs/dbt-athena/pull/650/files
If we want to process by batch of N days in parallel using Airflow concurrency, we need the tmp table create by each of the dbt run to be unique. Else, you are going to end up with N insert attempting to run with the same __dbt_tmp name, creating conflict and ultimately creating failure. …
=> Set unique temp table suffix to allow parallel incremental executions

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/adapters/python.sql, dbt/include/databricks/macros/relations/location.sql, tests/conftest.py, tests/functional/adapter/basic/test_incremental.py, tests/functional/adapter/incremental/test_incremental_strategies.py, tests/functional/adapter/persist_docs/fixtures.py, tests/functional/adapter/python_model/fixtures.py, tests/functional/adapter/python_model/test_python_model.py, tests/unit/macros/adapters/test_python_macros.py, tests/unit/macros/relations/test_table_macros.py
Resolves #812 
Adding config to have dbt-databricks add catalog and schema information to the path of external tables, to reduce the likelihood of conflicts arising from tables with the same name.  This is a huge pain in testing, but not sure if others hit this in the wild, hence why default is to not do this behavior.  We probably should have always been doing this, but it could potentially break existing workflows, another reason to default to False.
=> Behavior for external path

CHANGELOG.md, dbt/adapters/databricks/__version__.py, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/materializations/incremental/strategies.sql, dbt/include/databricks/macros/materializations/incremental/validate.sql, tests/functional/adapter/microbatch/fixtures.py, tests/functional/adapter/microbatch/test_microbatch.py
Resolves #824
Implements the microbatch incremental strategy: https://docs.getdbt.com/docs/build/incremental-microbatch
Core idea is that dbt will determine slices of time to break up an insert into multiple statements; we run a replace-where with those slices so that any old data is replaced by the newest version of that data.  This makes it much easier for users to back fill, and on failure, only rerun the slices that failed.
I have to cast the column to TIMESTAMP, as if your event_time column is a date, Databricks casts the conditions to date and then it looks like
replace where date >= X and date < X
I also hit an issue with column comments that I think was introduced in dbt-core 1.9.0b2 that I have fixed here.
=> Implement microbatch incremental strategy

CHANGELOG.md, dbt/adapters/databricks/impl.py, tests/functional/adapter/columns/test_get_columns.py
dbt cloud has a feature for testing connections. It and other features are currently failing due to adapter behavior flags not being registered for those runs. 
If we look at [these lines](https://github.com/databricks/dbt-databricks/blob/84fc024fb8e881ef5dc59d09a56bfcba99842091/dbt/adapters/databricks/impl.py#L183-L188), we see the use of a flag in the adapter class init.  This was par t of #808 
```
def __init__(self, config: Any, mp_context: SpawnContext) -> None:
super().__init__(config, mp_context)
if self.behavior.use_info_schema_for_columns.no_warn:  # type: ignore[attr-defined]
self.get_column_behavior = GetColumnsByInformationSchema()
else:
self.get_column_behavior = GetColumnsByDescribe()
```
This is not guaranteed to succeed. So we can use exception handling to ensure the …
=> Propose fix for connection testing issues in Cloud.

CHANGELOG.md, dbt/adapters/databricks/api_client.py, dbt/adapters/databricks/auth.py, dbt/adapters/databricks/behaviors/columns.py, dbt/adapters/databricks/column.py, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/credentials.py, dbt/adapters/databricks/events/connection_events.py, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/python_models/python_config.py, dbt/adapters/databricks/python_models/python_submissions.py, dbt/adapters/databricks/python_models/run_tracking.py, dbt/adapters/databricks/relation.py, dbt/adapters/databricks/relation_configs/base.py, dbt/adapters/databricks/relation_configs/incremental.py, dbt/adapters/databricks/relation_configs/materialized_view.py, dbt/adapters/databricks/relation_configs/partitioning.py, dbt/adapters/databricks/relation_configs/streaming_table.py, dbt/adapters/databricks/relation_configs/tags.py, dbt/adapters/databricks/relation_configs/tblproperties.py, dbt/adapters/databricks/utils.py, tests/functional/adapter/materialized_view_tests/test_basic.py, tests/functional/adapter/persist_constraints/test_persist_constraints.py, tests/functional/adapter/streaming_tables/test_st_basic.py, tests/functional/adapter/tblproperties/test_set_tblproperties.py, tests/profiles.py, tests/unit/fixtures.py, tests/unit/macros/base.py, tests/unit/test_adapter.py
Beginning in Python 3.9, many of the types from the typing package have been deprecated.  Since Python 3.9 is our lowest supported version now (and itself will be deprecated next year), need to comply with https://peps.python.org/pep-0585/#implementation
=> Removing deprecated types

CHANGELOG.md, dbt/include/databricks/macros/utils/split_part.sql
Hit issue with internal testing; turns out that the split_part macro in dbt-spark uses unsafe indexing (which is a totally reasonable choice), but the adapter tests expect it to be safe to index beyond the number of matched parts.  Switching to 'get' fixes the issue.
=> Update split part to use safe operation

dbt/include/databricks/macros/materializations/incremental/strategies.sql, docs/databricks-merge.md, tests/functional/adapter/incremental/fixtures.py
Resolves #841 
During canary usage of the 1.9.0b2, we discovered that some users had overwritten some existing macros to rely on the previous aliases (since they are used through dbt to interact with predicates).  This PR changes the defaults to the previous aliases.
=> Change merge alias defaults

dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/materializations/incremental/validate.sql, requirements.txt, setup.py, tests/functional/adapter/microbatch/test_microbatch.py
We would like to release our 1.9.0 soon, but dbt-core 1.9.0 has been postponed to December.  In this PR I'm lowering our dependency to released versions, and hiding microbatch as a valid strategy if your installed version is too low (because it will super break otherwise).
=> Downgrade dbt-core dependency to concrete required version (i.e. first one with behavior flags)

CHANGELOG.md, requirements.txt, setup.py, tests/functional/adapter/iceberg/test_iceberg_support.py, tests/unit/python/test_python_config.py
Dbt asked me to not require pydantic > 2 (as it was causing issues).  So I wrote all of my pydantic in v1; however, if pydantic v2 got installed, a bunch of warnings would be emitted.  So now restricting to < 2.
Marked failing iceberg tests as skip for now (since there is an issue in prod).
=> Cleanup warnings and test issues

CHANGELOG.md, dbt/adapters/databricks/__version__.py, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/adapters/multiple_statement.sql, dbt/include/databricks/macros/materializations/hooks.sql, dbt/include/databricks/macros/materializations/seeds/helpers.sql, dbt/include/databricks/macros/materializations/seeds/seeds.sql, docs/seed_flow.md, tests/functional/adapter/fixtures.py, tests/functional/adapter/persist_docs/test_persist_docs.py, tests/functional/adapter/simple_seed/test_seeds.py
Introduces the V2 Materialization flag (which is primarily going to be used with create table / incremental), and handles the first materialization to be pivoted based on the flag: Seeds.  Will be going through each materialization in a separate PR to keep the changes scoped.
Go here to compare the difference in flows: https://github.com/databricks/dbt-databricks/blob/726e6e16d5aec864a37aadb443991d0da265e4b6/docs/seed_flow.md
Seeds are pretty close to ideal already, but had some no op statements that I removed (since we don't have transactions or indexes).
=> V2 Materialization flag introduced

CHANGELOG.md, dbt/include/databricks/macros/materializations/incremental/incremental.sql
Resolves #
Set unique table suffix to allow parallel incremental execution
Our daily ETL need to execute parallel multiple dbt run of specific incremental model(`incremental_strategy=merge`), in which we pass the date and country as var argument.
If we want to process by batch of N countries and dates in parallel using Airflow concurrency, we need the temp views created by each of the dbt run to be unique. Else, you are going to end up with N insert attempting to run with the same __dbt_tmp name, creating conflict and ultimately creating failure.
=> Set unique temp table suffix to allow parallel merge execution

CHANGELOG.md, dbt/adapters/databricks/python_models/python_submissions.py, tests/unit/python/test_python_job_support.py
Hearing again from users about multiple python models having concurrency issues.  We definitely want to queue if necessary, but not sure if this is actually the problem.  Setting this shouldn't hurt though.
=> Try setting queue enabled for Python notebook jobs

dbt/adapters/databricks/api_client.py, dbt/adapters/databricks/behaviors/columns.py, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/python_models/python_submissions.py, dbt/include/databricks/macros/adapters/columns.sql, dbt/include/databricks/macros/adapters/persist_docs.sql, tests/functional/adapter/python_model/fixtures.py, tests/functional/adapter/python_model/test_python_model.py, tests/unit/api_client/test_command_api.py
Fixing two regressions related to Command submission of python models.
1.) Exceptions were not properly getting propagated to the user
2.) I had accidentally brought back the race condition that the community had already fixed for us.
=> Fix Python regressions in 1.9.0beta

CHANGELOG.md, dbt/adapters/databricks/column.py, dbt/adapters/databricks/utils.py, dbt/include/databricks/macros/adapters/columns.sql, dbt/include/databricks/macros/adapters/persist_docs.sql, dbt/include/databricks/macros/relations/constraints.sql, pyproject.toml, tests/unit/macros/relations/test_constraint_macros.py, tests/unit/test_column.py, tests/unit/test_utils.py
Resolves #859 
Ensures that column names are backticked when added via alter.  There are probably other places this needs to be done, but it's unclear to me whether we should prioritize user input ('quote' attribute on ColumnInfo) or safety, so only applying change to a single place.  Also refactored existing column quoting usages to have logic live in Python to make it more testable.
=> Ensure column name is backticked during alter

CHANGELOG.md, requirements.txt, setup.py
Testing if we can remove previous pins in backport to 1.8.x.
=> Remove superseded library pins

CHANGELOG.md, dbt/adapters/databricks/relation.py
Resolves #873
To keep dbt codegen from falling over, we need to include types that might be found in information_schema in the DatabricksRelationType enum.
=> dbt codegen only manually handles limited sets of Databricks types

CHANGELOG.md, dbt/include/databricks/macros/materializations/incremental/strategies.sql, docs/databricks-merge.md, tests/functional/adapter/incremental/fixtures.py, tests/functional/adapter/incremental/test_incremental_strategies.py
Resolves #860 
This PR will address the missing use case shared in the issue #860. When there's no match by source and condition holds now it will be possible to set update rule manually (will be executed syntactically as part of `update set` block).
=> MERGE EXTENSION: when not matched by source - update

CHANGELOG.md, dbt/adapters/databricks/api_client.py, dbt/adapters/databricks/column.py, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/credentials.py, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/python_models/run_tracking.py, dbt/adapters/databricks/relation.py, pyproject.toml, tests/functional/adapter/ephemeral/test_ephemeral.py, tests/functional/adapter/hooks/test_model_hooks.py, tests/functional/adapter/hooks/test_run_hooks.py, tests/functional/adapter/python_model/test_python_model.py, tests/unit/api_client/test_workspace_api.py, tests/unit/test_auth.py
Adds and applies the UP ruff ruleset, which ensures that we're not using any deprecated python.  Also removed pandas pin for consistency with 1.8.x branch.
=> More cleanup work for forward compatibility

CHANGELOG.md, dbt/adapters/databricks/column.py, dbt/adapters/databricks/constraints.py, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/relation.py, tests/unit/test_adapter.py, tests/unit/test_column.py, tests/unit/test_constraints.py, tests/unit/test_relation.py
When I went to apply the constraint logic from the previous PR, I discovered that Databricks does not like receiving multiple constraints for a single column in the table create syntax; however, you can add arbitrarily many table level constraints, so in this PR I aim to do the following:
* if a column has a not_null constraint, directly set not_null on the column
* any other column constraint gets converted to a TypedConstraint, a subclass of ModelLevelConstraint that enforces the requirements of the particular constraint, and holds the rendering logic.  The conversion required setting 'columns=[name]'. Because python makes operator overloading a pain in the butt, I'm going back to OOP for the render logic.
* If a model level constraint is not_null, convert to setting not_null on each …
=> Redo constraints (since columns can only take one constraint at create time)

CHANGELOG.md, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/credentials.py, dbt/adapters/databricks/global_state.py, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/logging.py, tests/unit/test_adapter.py
Centralize env var reading since it is actually a global state reference, and we should be aware of as such.  We will lazy set once, and return values from then on (since allowing users to change the value during a run, and have that change reflected seems crazy unpredictable).
=> Refactor reading env vars

dbt/include/databricks/macros/materializations/seeds/helpers.sql, dbt/include/databricks/macros/relations/constraints.sql
Discovered when I was trying to add a new config entry that:
```
config.get('foo')
```
and
```
config.get("foo")
```
behave differently in Jinja templates.  This is crazy.  I believe this only applies to the config dictionary, but to be safe, every place we use `get` in the templates, I want to use single quotes.
=> Use single quotes in gets in templates

CHANGELOG.md, dbt/include/databricks/macros/adapters/columns.sql, dbt/include/databricks/macros/adapters/persist_docs.sql, dbt/include/databricks/macros/relations/constraints.sql, dbt/include/databricks/macros/relations/liquid_clustering.sql, dbt/include/databricks/macros/relations/materialized_view/alter.sql, dbt/include/databricks/macros/relations/materialized_view/drop.sql, dbt/include/databricks/macros/relations/materialized_view/refresh.sql, dbt/include/databricks/macros/relations/streaming_table/drop.sql, dbt/include/databricks/macros/relations/streaming_table/refresh.sql, dbt/include/databricks/macros/relations/table/create.sql, dbt/include/databricks/macros/relations/table/drop.sql, dbt/include/databricks/macros/relations/tags.sql, dbt/include/databricks/macros/relations/tblproperties.sql, dbt/include/databricks/macros/relations/view/create.sql, dbt/include/databricks/macros/relations/view/drop.sql
We have historically relied on `{{ relation }}` to substitute the 3-layer relation name into templates.  `{{ relation.render() }}` is preferred because it correctly backticks, and I believe might be replaced at run-time when users ask for the `--empty` flag, with a `limit 0` version.
=> Switch to render for safest relation str substitution

CHANGELOG.md, dbt/include/databricks/macros/materializations/snapshot.sql, tests/functional/adapter/simple_snapshot/test_new_record_mode.py, tests/functional/adapter/simple_snapshot/test_various_configs.py
Resolves #901 #902
Apparently a late addition to the 1.9 (or at least late for adapter implementors to find out about) was a bunch of new snapshot behavior.  Unfortunately the validation tests were not at all aligned with Databricks limitations, so had to bring in a bunch of code and tailor it, rather than just import the tests like we do ideally.  This should allow the list of unique column behavior and the hard delete strategy.  Note: most of the materialization is lifted as is from dbt-adapters default implementation, but keeping some Databricks specializations (like having to apply check constraints later).  This materialization will be getting a face lift in 1.10.x, along with the other materializations, so I wanted to minimize the special effort required now.
TL;DR, the test code is …
=> Adding missing 1.9 Snapshot behavior

CHANGELOG.md, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/global_state.py, dbt/adapters/databricks/impl.py
For a long time we've had code that suggested that you could either reuse sessions or not by setting an env variable.  This hasn't worked for a long time, and since I need to refactor some of this code to improve cancellation behavior, I want to first compress to a single ConnectionManager, so that I don't need to make changes against both.  I eventually want to get rid of session reuse, but its too large to do as part of 1.9.x, where I want to improve cancellation behavior, so for now, let the code include only the paths that are actually reachable.
Note: no new code here, just collapsing into the parent class, and keeping the union of the code from the child and the parent.  Each method comes either from the parent (if the previous child didn't override) or the child (if the child did …
=> Compress to one connection manager

CHANGELOG.md, dbt/adapters/databricks/impl.py
Executing dbt locally in a Windows machine is including front slash when using os.path.join function for separating different elements of the location and so generating issues when creating the tables. 
Using posix join it will always use back slash to separate the elements of the location and so work in any operating system.
=> Update impl.py to use POSIX standard on location

CHANGELOG.md, dbt/adapters/databricks/__version__.py
1.9.3 had to be yanked because I published it without the change that was the whole reason for 1.9.3.  This PR is to fix the changelog to reflect that.
=> Fixing Changelog

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/relations/liquid_clustering.sql, dbt/include/databricks/macros/relations/optimize.sql, tests/functional/adapter/liquid_clustering/fixtures.py, tests/functional/adapter/liquid_clustering/test_liquid_clustering.py, tests/unit/macros/relations/test_table_macros.py
Resolves #932
Adds config `auto_liquid_cluster` to allow for tables to be `CLUSTER BY AUTO` on creation or update (i.e. incremental run)
=> Allow auto liquid clustering

CHANGELOG.md, dbt/adapters/databricks/api_client.py, dbt/adapters/databricks/python_models/python_config.py, dbt/adapters/databricks/python_models/python_submissions.py, tests/functional/adapter/python_model/fixtures.py, tests/functional/adapter/python_model/test_python_model.py, tests/unit/python/test_python_job_support.py
Learned from working with jobs team today that to use environments, we need the tasks to take an environment key...but also learned this doesn't work yet with serverless notebooks.  This code is to prepare for that feature to come to Databricks, to minimize time without this feature for users.  Normally I hate doing that, but there are user workloads blocked on this.
=> Prepare for environments with serverless notebooks

tests/functional/adapter/basic/fixtures.py, tests/functional/adapter/basic/test_docs_generate.py
In 16.x DBR, owner seems to no longer be available as part of doc generation.  This will require further investigation, but to keep Multi-DBR tests from breaking, for now allowing None.
=> Don't fail doc generation tests for lack of owner

CHANGELOG.md, dbt/adapters/databricks/behaviors/columns.py, dbt/adapters/databricks/impl.py, dbt/adapters/databricks/relation.py, dbt/include/databricks/macros/adapters/catalog.sql
Colin brought to my attention that there is a full_data_type column now in the info schema that is more apt, since it gives the details of struct.
=> Dealing with changes to the info schema

CHANGELOG.md, dbt/adapters/databricks/constraints.py
Quotes/backticks are not applied for foreign key and primary key constraints in 1.10.0a1, even if the column's config specifies `quote: true`. By retrieving the (optional) `quote` argument from the column config in `parse_column_constraints` we can apply backticks to the constraint definition.
Resolves #965 
Modifies the `parse_column_constraints` to dynamically apply backticks on columns with foreign key and primary key constraints, if specified in the model's configuration:
```
columns:
- name: speciål_char_pk
data_type: string
quote: true
constraints:
- type: not_null
- type: primary_key
```
- [] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-databricks next" section.
=> quote columns for foreign key and primary key constraints, if quote: true in column config

CHANGELOG.md, dbt/adapters/databricks/credentials.py, dbt/adapters/databricks/relation_configs/incremental.py, dbt/adapters/databricks/relation_configs/liquid_clustering.py, dbt/adapters/databricks/relation_configs/tblproperties.py, dbt/include/databricks/macros/materializations/incremental/incremental.sql, dbt/include/databricks/macros/relations/liquid_clustering.sql, dbt/include/databricks/macros/relations/table/alter.sql, tests/unit/relation_configs/test_incremental_config.py
For incremental models, liquid clustering column setting was running on every incremental run.  We can use the check for difference approach basically for free, since it reuses data we were already gathering, so moving to that.
=> Moving liquid clustering to the check for difference approach

dbt/include/databricks/macros/adapters/metadata.sql
Last PR showed a failure when integrating.  This should fix that test failure.  Issue was that my 'run_query_as', returns the .table from load_result, but in this particular case, we need load_result itself.
=> Fix failure in checking for freshness.

dbt/include/databricks/macros/adapters/python.sql, dbt/include/databricks/macros/materializations/incremental/strategies.sql, dbt/include/databricks/macros/relations/constraints.sql, dbt/include/databricks/macros/relations/materialized_view/create.sql, dbt/include/databricks/macros/relations/optimize.sql, dbt/include/databricks/macros/relations/streaming_table/alter.sql, dbt/include/databricks/macros/relations/streaming_table/create.sql, dbt/include/databricks/macros/relations/table/create.sql, dbt/include/databricks/macros/relations/table/rename.sql, tests/unit/macros/adapters/test_catalog_macros.py, tests/unit/macros/adapters/test_columns_macros.py, tests/unit/macros/adapters/test_metadata_macros.py, tests/unit/macros/adapters/test_persist_docs_macros.py, tests/unit/macros/base.py, tests/unit/macros/materializations/incremental/test_insert_into_macros.py, tests/unit/macros/materializations/incremental/test_merge_macros.py, tests/unit/macros/materializations/incremental/test_microbatch_macros.py, tests/unit/macros/materializations/incremental/test_replace_where_macros.py, tests/unit/macros/relations/test_table_macros.py, tests/unit/macros/relations/test_tags_macros.py, tests/unit/macros/relations/test_view_macros.py
Continuing to work on improving unit tests for macros and increasing coverage.  Found a bunch of places we weren't using render() yet, as well.
=> More unit tests, more cleanup

dbt/adapters/databricks/behaviors/columns.py
While investigating for solutions to complex types in temporary views, discovered this issue where we delegate to super, it calls the overridden _parse_columns of the child, which leads to issues.  Hence, renaming the method for the child rather than overriding.
=> Fix issue where we delegate to the wrong method.

CHANGELOG.md, dbt/adapters/databricks/api_client.py, tests/unit/api_client/test_job_runs_api.py
Resolves #
https://github.com/databricks/dbt-databricks/issues/984
There is an issue where even after canceling a Notebook Job executed by the DBT Python model, it still appears successful. I have modified it to also check for CANCELLED in the terminal_states.
tested
```
hatch run unit
....
[gw1] [100%] PASSED tests/unit/test_adapter.py::TestDatabricksAdapter::test_describe_table_extended_may_limit 
===================== 469 passed, 6 skipped in 9.72s ======================
```
=> Fix: DBT Python Model Canceled Notebook Job Treated as Successful

CHANGELOG.md, dbt/adapters/databricks/connections.py, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/materializations/incremental/incremental.sql
In 1.10.0, we starting failing users that previously were passing for INSERT OVERWRITE with SQL Warehouses.  They should have always failed, since without dynamic partition setting, INSERT OVERWRITE is just truncate + insert, which is no better than the table materialization.  Hence, we guard every call to this setting with a check for compute type, and if not cluster, raise an information error message.
=> Fix regression related to insert_overwrite

CHANGELOG.md, dbt/adapters/databricks/impl.py, tests/unit/test_adapter.py
Resolves #994
Fixes a bug where temporary tables with unique identifiers would not be dropped on session close due to the table name containing illegal characters generated by the `uuid`.
=> Replace illegal characters in unique temporary table names

CHANGELOG.md, dbt/adapters/databricks/relation.py, dbt/adapters/databricks/relation_configs/column_comments.py, dbt/include/databricks/macros/adapters/persist_docs.sql, dbt/include/databricks/macros/adapters/relation.sql, dbt/include/databricks/macros/materializations/table.sql, dbt/include/databricks/macros/materializations/view.sql, dbt/include/databricks/macros/relations/replace.sql, dbt/include/databricks/macros/relations/tags.sql, dbt/include/databricks/macros/relations/tblproperties.sql, dbt/include/databricks/macros/relations/view/rename.sql, dbt/include/databricks/macros/relations/view/replace.sql
Resolves #997 
Thanks to @geo-martino for raising issues around view replacement with unique temp locations, I found a bunch of small issues with view replacement generally.
Context: In materializations V2, we were making some really odd choices around view replacement due to a number of small bugs.  A customer noticed that when using unique names for temporary objects, we ended up trying to drop a different object than the one we had used, causing an error.  This led me down a long rabbit hole of finding a bunch of bugs that didn't show up on tests because for the majority of cases, the external behavior was the same, but the process was not what we had intended.  These are basically options that the user can specify to control how they want to materialization to play out, without …
=> Fixing view replace logic

dbt/adapters/databricks/api_client.py
Resolves #
https://github.com/databricks/dbt-databricks/issues/1020
Output the stack trace log when the DBT Python model job fails.Previously made the following fix. While it resolved the issue, it also caused the stack trace to no longer be output when the job fails, making it harder to investigate the root cause.Sorry for that.
```
Python model run ended in result_state FAILED
```
https://github.com/databricks/dbt-databricks/pull/985
By applying this modification, the job will fail with an error upon cancellation, and if it fails for any other reason, the error will be displayed along with the full stack trace.
FAILED
```
08:36:37 Databricks adapter: Job submission response=b'{"run_id":409733473259621}'
08:36:58 1 of 1 ERROR creating python table model<catalog>.<schema>.model.......... …
```
=> Output the stack trace log when the DBT Python model job fails

CHANGELOG.md, dbt/adapters/databricks/api_client.py, tests/unit/api_client/test_cluster_api.py, tests/unit/api_client/test_command_context_api.py, tests/unit/api_client/test_library_api.py
Resolves #1028
We currently check cluster status in 2 places for python submissions
- `CommandContextApi.create`
- `ClusterApi.wait_for_cluster`
This PR introduces a new `LibraryApi` to check the status of additional libraries added via the managed libraries API. It is invoked in the two places mentioned above to prevent the job from starting prematurely
Tested this E2E manually. The logs indicate that the additional libraries start off with status `PENDING`. The command is not executed until the libs are installed
```
[0m11:46:19.373884 [debug] [Thread-6  ]: Databricks adapter: Waiting for all libraries to be installed: {'cluster_id': '0520-174627-h5fgyjhc', 'library_statuses': [{'library': {'pypi': {'package': 'pyarrow'}}, 'status': 'PENDING', 'messages': ['Library status is …
```
=> Wait for library installation on python submission

tests/functional/adapter/simple_snapshot/test_various_configs.py
Resolves #
Fix integration tests from breaking change in https://github.com/dbt-labs/dbt-adapters/commit/4b3fc1e9c11a6b454672e02bca5af186dc5caf96
=> Fix integration tests

CHANGELOG.md, dbt/adapters/databricks/connections.py, tests/conftest.py, tests/functional/adapter/incremental/test_incremental_strategies.py
Resolves #1032
Looks like the bug is coming from the fact that the connection credentials always point to the project level compute details. When overriding compute at the model level, we need to check elsewhere to verify whether it is a cluster or SQL warehouse
=> Fix insert overwrite compile check when using model level compute override

dbt/include/databricks/macros/materializations/incremental/incremental.sql, tests/functional/adapter/incremental/test_incremental_strategies.py
Resolves #
It seems like some customers are using INSERT_OVERWRITE with SQL warehouses to leverage the side effect of reusing the same table for subsequent runs. Downgrading the compiler error to a warning
=> Downgrade INSERT_OVERWRITE error to warning for SQL warehouses

.github/workflows/integration.yml
Resolves #
This should help with debugging test failures, especially those that are not reproducible locally
=> Export dbt logs as artifacts in integration test workflows

CHANGELOG.md, dbt/adapters/databricks/relation.py, tests/functional/adapter/metric_views/test_metric_views.py
Resolves #1045
Add metric view as a relation type so that models can be run against catalogs that have metric views
=> Add metric_view as a relation type

CHANGELOG.md, dbt/adapters/databricks/constraints.py, tests/functional/adapter/incremental/fixtures.py, tests/functional/adapter/incremental/test_incremental_constraints.py, tests/unit/relation_configs/test_constraint.py
Resolves #1081
It looks like the root cause behind #1081 is because of how we determine equality between TypedConstraint objects. During incremental runs, we rely on the equality check to determine which constraints to drop or apply https://github.com/databricks/dbt-databricks/blob/6981678333b6f1b715b272041b166576df925e37/dbt/adapters/databricks/relation_configs/constraints.py#L30-L32
The current default equality check is considering fields like `warn_unenforced`. This does not work because this is a user supplied config that has no meaning when we are creating a `TypedConstraint` from existing Databricks relations. The Fix is to override the `__eq__` to match the `__hash__` which already ignores such fields
=> Fix TypedConstraint equality check

CHANGELOG.md, dbt/adapters/databricks/relation.py, dbt/include/databricks/macros/materializations/clone.sql, dbt/include/databricks/macros/materializations/clone/clone.sql, dbt/include/databricks/macros/materializations/clone/strategies.sql, tests/unit/macros/materializations/test_clone_macros.py, tests/unit/macros/relations/test_table_macros.py, tests/unit/utils.py
This PR adds the ability to clone the external tables to the package. Without that, the `dbt clone` command fails as Databricks requires providing the location of the target if we are cloning the external table.
To achieve that, I've introduced the `is_external_table` property of the `DatabricksRelation` that provides the information if the table is external. Then, I've added the new macro named `databricks__create_or_replace_clone_external` that handles the logic of the external cloning and uses the `location_clause` macro to determine where to perform the clone based on the target table configs.
The decision which macro to choose is happening in the `clone` macro itself: if the `is_external_table` attribute of the relation returns True, we call the `_external` macro. If not, we perform …
=> Add cloning for the external tables

dbt/include/databricks/macros/adapters/columns.sql
Resolves #1098 
We should leave it up to DBSQL to decide when append/delete columns is allowed rather than short circuit, so that things like parquet column append can work.
=> Ensure we can append with parquet, and delegate to DBSQL for possible errors

CHANGELOG.md, dbt/adapters/databricks/impl.py, dbt/include/databricks/macros/relations/materialized_view/create.sql, dbt/include/databricks/macros/relations/streaming_table/create.sql, tests/functional/adapter/materialized_view_tests/fixtures.py, tests/functional/adapter/materialized_view_tests/test_basic.py, tests/functional/adapter/streaming_tables/fixtures.py, tests/functional/adapter/streaming_tables/test_st_basic.py
Resolves #1100
MV/STs currently uses `get_column_schema_from_query` to get data types, but it is broken for complex data types (i.e. struct, map, array). For example, if the input type is `map<int,int>`, the output will be a `map` which is not a full data type that is required on create.
The temporary workaround is to write a few results to a temporary view, then run a `DESCRIBE TABLE EXTENDED .. AS JSON` to get the full non-truncated data types. Ideally, once `DESCRIBE QUERY EXTENDED .. AS JSON` is supported in Databricks, we should use that instead
=> Fix MV/ST materializations with complex data types

CHANGELOG.md, dbt/adapters/databricks/impl.py, tests/unit/test_adapter.py
Resolves #
Current support for `DESCRIBE TABLE EXTENDED .. AS JSON`:
- Streaming tables: DBR 17.1+
- Materialized views: Not supported
- All other relation types: DBR 16.2+
Fix the macro branching logic to reflect this
=> Fix AS JSON branching logic for MV/STs

CHANGELOG.md, dbt/adapters/databricks/behaviors/columns.py, tests/unit/test_adapter.py
Resolves #1128
It looks like the branching logic does not cover all the possible failure scenarios of `AS JSON`. From manual testing and bug reports, it looks like
1. `PARSE_SYNTAX_ERROR` is thrown when DBR version does not support it
2. `UNSUPPORTED_FEATURE` is thrown when DBR version supports it, but relation type does not (e.g. foreign table, materialized views)
Instead of trying to guess all the edge cases where `AS JSON` is unsupported, add a try-catch to fallback to the legacy macro when the error message contains one of these errors
=> Add fallback logic for known error types for AS JSON

CHANGELOG.md, dbt/adapters/databricks/connections.py, tests/unit/test_query_config.py
Resolves #
Most of our custom connection management logic is to facilitate per-thread caching of connections (e.g. determine when it is safe to reuse a connection). This optimization has proven to be insignificant to overall execution time, so we are moving back to a simpler model that aligns with dbt core's base connection management. This PR cleans up all of the caching logic
=> Simplify connection management to align with base adapter

CHANGELOG.md, dbt/adapters/databricks/relation_configs/view.py, dbt/include/databricks/macros/materializations/view.sql, dbt/include/databricks/macros/relations/components/column_tags.sql, dbt/include/databricks/macros/relations/view/create.sql, tests/functional/adapter/column_tags/fixtures.py, tests/functional/adapter/column_tags/test_column_tags.py
Resolves #
Previously, we did not add column tag support for views because `ALTER VIEW` does not support it. However, it turns out that `ALTER TABLE` works on views for setting column tags. This PR adds the missing column tag support for views and updates column tag functional tests to add coverage for updated column tag configs between runs
=> Add column tag support for views

pyproject.toml
Resolves #
Protobuf version was updated by our dbt dependencies:
- https://github.com/dbt-labs/dbt-adapters/pull/1259
- https://github.com/dbt-labs/dbt-common/pull/300
- https://github.com/dbt-labs/dbt-core/pull/11916
This broke our CI because pip is installing published pypi versions of transitive dependencies. The fix is to install dependencies in order, starting from leaf nodes
=> Adjust order of dbt dependency installation

.github/workflows/ci-pr-linting.yml, CHANGELOG.md
Related #1111 
Add PR linting check to ensure conventional commits for a cleaner git history. 
Still need to enforce [squash and merge](https://docs.github.com/fr/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests) but I don't have the rights. 
I'll check how to use release-please to generate the changelog using release-please but managing the versions on our side !
=> feat(1111): add pr linting to enforce conventional commits

pyproject.toml
Resolves #
Tighten versions for some upstream dependencies that have broken us in the past. For dbt packages, pin patch version as they frequently contain significant changes. The only exception is `dbt-common` which rarely has patch versions (https://pypi.org/project/dbt-common/#history), so just pinning minor version for that
=> chore: Tighten version range for higher risk dependencies

docs/testing.md, tests/conftest.py
- Allow overriding default test profile via DBT_DATABRICKS_PROFILE environment variable
- Change default test profile from databricks_cluster to databricks_uc_sql_endpoint
- Update testing documentation to explain profile selection for CLI vs IDE testing
- Maintains backward compatibility with existing --profile flag and hatch commands
=> chore: Add DBT_DATABRICKS_PROFILE env var for test profile selection

.github/workflows/integration.yml
According to Cursor, these are the changes we need such that user PRs can run our integration tests in our target, but only after approval.
=> chore: Modify integration workflow to simplify running external PRs

CHANGELOG.md, dbt/adapters/databricks/utils.py, tests/unit/test_connection_manager.py, tests/unit/test_utils.py
Resolves #
Current logic for `is_cluster_http_path` is backwards. When original compute is a cluster and the model-level override is a SQL warehouse, it wrongly returns true. We should use `http_path` as the source of truth instead of the cluster ID. Cluster ID should only be used as a fallback if the expected keywords do not exist in the path
=> Fix: model-level override logic for is_cluster

dbt/include/databricks/macros/relations/materialized_view/alter.sql, dbt/include/databricks/macros/relations/streaming_table/alter.sql, dbt/include/databricks/macros/relations/tags.sql, tests/functional/adapter/tags/test_databricks_tags.py
I don't know how this was happening, since the code for change detection seems to not return a TagsConfig when I go into via debug, but we were calling alter with an empty set tags set, which was raising exceptions.
=> fix: ST set tags were being applied when empty

dbt/include/databricks/macros/materializations/functions/scalar.sql, pyproject.toml
Resolves #N/A
I made a mistake in dbt-core and dbt-adapters when initially implementing function nodes. I mis-named some properties. Unfortunately, we just caught it. The result is that we need to fix accessing some properties in dbt-databricks
* https://github.com/dbt-labs/dbt-core/pull/12065
* https://github.com/dbt-labs/dbt-adapters/pull/1366
=> fix: Ensure we access correct function properties in macros

CHANGELOG.md, dbt/include/databricks/macros/materializations/snapshot.sql
Resolves #1187 
Add checking the `databricks_tags` config on snapshots and also apply them. With this change, the following snapshot definition:
```yaml
snapshots:
- name: yet_another_snap
relation: ref('foo')
config:
strategy: check
check_cols: all
unique_key: id
databricks_tags:
some_key: some_value
```
Results in the tag being applied, e.g:
```sh
$ dbt snapshot
...
03:31:23  On snapshot.analytics.yet_another_snap: /* {"app": "dbt", "dbt_version": "1.10.11", "dbt_databricks_version": "1.10.12", "databricks_sql_connector_version": "4.0.5", "profile_name": "all", "target_name": "db", "node_id": "snapshot.analytics.yet_another_snap"} */
merge into `dev`.`dbt_jyeo_prod`.`yet_another_snap` as DBT_INTERNAL_DEST
using `yet_another_snap__dbt_tmp` as DBT_INTERNAL_SOURCE
on …
```
=> feat: Add tagging methods to snapshot

AGENTS.md, dbt/adapters/databricks/api_client.py, dbt/adapters/databricks/python_models/python_submissions.py, tests/unit/api_client/test_retry_logic.py, tests/unit/api_client/test_workspace_api.py
This change improves the robustness of Python model execution by adding retry logic with exponential backoff for operations that may encounter transient failures such as rate limiting, network issues, or temporary service unavailability.
This addresses intermittent test failures seen in CI/CD when multiple tests run concurrently and hit rate limits or temporary API issues.  Really hoping this works.
=> fix: Add retry logic for transient API errors in Python model execution
